### ISSUE TITLE
request missing

### ISSUE THREAD

**Issue by ambhaiji** [yasinkuyu/binance-trader#1]
from BinanceAPI import *
  File "/Users/ambhaiji/Downloads/binance-trader-master/BinanceAPI.py", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by lemarier** [comment]
Try with

`sudo easy_install -U requests`

**Comment by bestlinkXx** [comment]
Hello,

I had the same problem on my iOS. I can fix it with this install.

Could you explain me how can I fix it please ?

**Comment by ambhaiji** [comment]
Hi please add prerequisites to the readme for easier installation for other users
