### ISSUE TITLE
ILEGAL CHARACTERS FOUND

### ISSUE THREAD

**Issue by Banginpadr** [yasinkuyu/binance-trader#10]
price:0.00005940 buyp:0.00005905 sellp:0.00005984-bid:0.00005904 ask:0.00005985 BTC:$14232.0
Error: Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.

i keep getting this error for some reason i cant explain. 
@yasinkuyu

**Comment by SlimxaQ** [comment]
That's because Binance API Is sending 'price' as STRING We need to wait for author to convert 'price' To INT.

Let's wait 👍

**Comment by Banginpadr** [comment]
@derciak thank you since i didnt clone could you be so kind to drop me a line here to let me know when that is done?i have no wait to know when it will be done

**Comment by Derciak** [comment]
@Banginpadr Try edit 59 line to:

ret = float(client.get_open_orders(symbol))

Maybe will work..

**Comment by Banginpadr** [comment]
@Derciak nothing bro. i still get the min_notional error

**Comment by caiorondon** [comment]
I found a couple of numerical type issues (profit argument, to name one). 

I'm currently trying to debug it. If i get somewhere before the author, I'll post here the solution.

**Comment by TexGoose** [comment]
![image](https://user-images.githubusercontent.com/34754964/34277660-5d85d452-e66c-11e7-951c-0b2557142882.png)

**Comment by kulttuuri** [comment]
Same error.

**Comment by Foof811** [comment]
Just got one of these recently too.
