### ISSUE TITLE
The script forget to sell 0.01 quantity

### ISSUE THREAD

**Issue by Memoi** [yasinkuyu/binance-trader#101]
Hello,

If I want to buy 1 or 3 for example the script sell the same value -0.01 (see screenshot)

This is my command line for quantity 3 :
Powershell python ./trader.py --symbol NEOETH --quantity 3 --profit 2

![0 01 missing](https://user-images.githubusercontent.com/35448059/34981553-20e8f0e2-faa8-11e7-8ffb-d71772bf92bd.png)

**Comment by nealgentry** [comment]
3.00 minus fee 0.01 = 2.99

**Comment by linhndd** [comment]
Buy some BNB coin for fee

**Comment by Memoi** [comment]
I have 4 BNB.

**Comment by Charlita** [comment]
Make sure on your binance account settings you have "Use BNB to pay for fees" turned on

**Comment by kfiresmith** [comment]
For the record, I observed the same thing and went back multiple times to toggle BNB-for-fees on, off, on again - no change.

**Comment by Charlita** [comment]
Oh I didn't notice in the OP that the fee was in BNB. Very interesting

**Comment by Memoi** [comment]
It's on "Use BNB to pay for fees"

**Comment by kfiresmith** [comment]
Did this get fixed or just closed as a wontfix item?  It's clear that numerous people with BNB-for-fees enabled observed this behavior repeatedly.
