### ISSUE TITLE
Problem with the decreasing coin value

### ISSUE THREAD

**Issue by shawnryan131** [yasinkuyu/binance-trader#105]
Right now I am running the bot on its default settings for the coin MANA/ETH. Here is the code: python trader.py --symbol MANAETH --quantity 200 --profit 1.1

In other words, I have it running to gain 1.1% profit on each 200 coin purchase.

The PROBLEM is it keeps increasing the value of the coin at which it tries to buy and sell...for example: If it peaks/makes a sale at 0.00016017ETH it will then buy immediately at lets say 0.00015900 and put up sales at something like 0.00016300 or something, but lets say MANA never gets to there for the rest of the entire god damn day. I just sit there losing all my profits because the code has no way to deal with a decrease in coin value...

What I need is some way for the script to slowly decrease the value that it can sell at over time as well as perhaps increasing the profit margin so it has to go lower before buying more.

I see on the download page something called "Range Mode" where you put in a range and I believe the buy/sell has to stay within that range. I.E. python trader.py --symbol MANAETH --mode range --quantity 200 --buyprice 0.0006500--sellprice 0.0006700. ...The problem here is I think you would miss out on a lot of profit when the coin falls outside of that range during its daily peaks and troughs.

The only other thing I see on the page is this: --increasing Buy Price Increasing +(default 0.00000001) --decreasing Sell Price Decreasing -(default 0.00000001)

I don't know if this would solve my problem...Since the bot has absolutely zero issues with making profit when the curve is going up I guess if I get rid of the buy price increasing and increase the sell price decreasing, but, again, I don't know what it does without testing it....Can someone confirm that function???

Anyway... Any tips would be helpful. Please let me know if anyone else has some code for me to try. Thanks

**Comment by SpencerBoyd** [comment]
I agree with this suggestion. At the moment I'm finding the best use to be taking profit from a coin thats on an upswing, but that you don't want to hold. Right now, for me its XVG - a coin I don't believe in, but seems to consistently profit.

**Comment by shawnryan131** [comment]
You guys have to find a way to make money on the decline man. Don't just have it keep buying higher and higher. there are DIPS. you can still make money on the dips. The way it runs right now makes it IMPOSSIBLE to make any money. I have sales just sitting there all day and the coin price never goes there. Code it in to wait a bit for it to drop a certain percent and THEN buy the god damn coin again and have it go up a percentage based on how much it has in the past 24/hr..cmon.

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/75863359d84c5c4c9fa552202eb09331217004fe
