### ISSUE TITLE
Issue encountered

### ISSUE THREAD

**Issue by aguilardmarkanthony** [yasinkuyu/binance-trader#106]
Can you please help? I encountered an error, kindly see below. Thank you.

HTTPSConnectionPool(host='www.binance.com', port=443): Max retries exceeded with url: /api/v1/depth?symbol=XRPBTC&limit=5 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Exception in thread Thread-21:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "trader.py", line 327, in action
    buyPrice = lastBid + option.increasing
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'HTTPSConnectionPool(host='www.binance.com', port=443): Max retries exceeded with url: /api/v1/depth?symbol=XRPBTC&limit=5 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Exception in thread Thread-21:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "trader.py", line 327, in action
    buyPrice = lastBid + option.increasing
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

**Comment by Memoi** [comment]
Hi,
You try it at home ? 

Because I had the same problem if I use it at my work because there is a proxy

**Comment by WeSpeakCrypto** [comment]
LOL. Try it using your hotspot from mobile data in your office. If it works, don't use this in your office.

**Comment by aguilardmarkanthony** [comment]
Sorry, but I got the same error I am now at home.
gt: HTTPSConnectionPool(host='www.binance.com', port=443): Max retries exceeded with url: /api/v1/ticker/24hr?symbol=INSBTC (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
price:0.00056200 buyp:0.00056201 sellp:0.00056650-bid:0.00056200 ask:0.00056250
Exception in thread Thread-137:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./app\Trading.py", line 300, in action
    print ('price:%.8f buyp:%.8f sellp:%.8f-bid:%.8f ask:%.8f' % (lastPrice, buyPrice, profitableSellingPrice, lastBid, lastAsk))
TypeError: float argument required, not NoneType

**Comment by yasinkuyu** [comment]
You will get this error if there is no Internet connection or if you can not connect to the binance server.
