### ISSUE TITLE
Range Mode Error

### ISSUE THREAD

**Issue by shawnryan131** [yasinkuyu/binance-trader#113]
I'm sorry I've been writing a bunch of these, but I wanted to try range mode and it isn't letting me do it. Here is the error:

binance-trader$ python trader.py --symbol MANAETH --mode range --quantity 190 --buyprice 0.00012910 --sellprice 0.00013600
usage: trader.py [-h] [--quantity QUANTITY] --symbol SYMBOL [--profit PROFIT]
                 [--stoploss STOPLOSS] [--increasing INCREASING]
                 [--decreasing DECREASING] [--orderid ORDERID]
                 [--wait_time WAIT_TIME] [--test_mode TEST_MODE]
                 [--prints PRINTS] [--debug DEBUG] [--loop LOOP]
trader.py: error: unrecognized arguments: --mode range --buyprice 0.00012910 --sellprice 0.00013600

What am I supposed to add? I;m really bad at inputting data into the actual code.

**Comment by yasinkuyu** [comment]
You should download again. Codes may not be up to date.

**Comment by shawnryan131** [comment]
If I download it again do I have to go through the entire process for installing n stuff? I had someone do that for me. what info is the code asking for that I dont have?

**Comment by Charlita** [comment]
I just tried the same line you have and it works for me, I would redownload it and just keep your config.py file and copy it to the new bot folder you download.

**Comment by yasinkuyu** [comment]
@shawnryan131 Did you try?
