### ISSUE TITLE
How to solve "m: Filter failure: PRICE_FILTER" error ?

### ISSUE THREAD

**Issue by Wrexen** [yasinkuyu/binance-trader#114]
Hey anyone can help me ? I get the error: "m: Filter failure: PRICE_FILTER"

This is how i run the trader:
trader.py --quantity 200 --symbol CMTBNB --profit 1.7 --orderid 0

Error:
price:0.01950000 buyp:0.01927001 sellp:0.01959759-bid:0.01927000 ask:0.01978000
m: Filter failure: PRICE_FILTER
price:0.01950000 buyp:0.01927001 sellp:0.01959759-bid:0.01927000 ask:0.01978000
m: Filter failure: PRICE_FILTER
price:0.01950000 buyp:0.01927001 sellp:0.01959759-bid:0.01927000 ask:0.01978000
m: Filter failure: PRICE_FILTER
m: Filter failure: PRICE_FILTER
price:0.01950000 buyp:0.01927001 sellp:0.01959759-bid:0.01927000 ask:0.01978000
price:0.01950000 buyp:0.01927001 sellp:0.01959759-bid:0.01927000 ask:0.01978000
m: Filter failure: PRICE_FILTER
price:0.01950000 buyp:0.01927001 sellp:0.01959759-bid:0.01927000 ask:0.01978000
m: Filter failure: PRICE_FILTER
price:0.01950000 buyp:0.01927001 sellp:0.01959759-bid:0.01927000 ask:0.01978000
m: Filter failure: PRICE_FILTER
price:0.01950000 buyp:0.01927001 sellp:0.01959759-bid:0.01927000 ask:0.01978000
m: Filter failure: PRICE_FILTER
price:0.01950000 buyp:0.01927001 sellp:0.01959759-bid:0.01927000 ask:0.01977000

**Comment by yasinkuyu** [comment]
default --increasing   Buy Price Increasing  +(default 0.00000001)
default --decreasing   Sell Price Decreasing -(default 0.00000001)

price : 0.01950000

therefore it should be like this;

--increasing 0.0001 or --decreasing 0.0001

**Comment by yasinkuyu** [comment]
check this https://github.com/yasinkuyu/binance-trader/commit/75863359d84c5c4c9fa552202eb09331217004fe

**Comment by Wrexen** [comment]
Thanks for your help mate. Its working now.
Can you help me with one more question ?
Can I adjust the trader so that he only makes one trade and waits until this is done ?

**Comment by yasinkuyu** [comment]
@Wrexen next version will have some improvements.

**Comment by monatcan** [comment]
How did you fix it for FILTER_FAILURE?

**Comment by rparsel** [comment]
any ideas why im getting this message when the app trys to sell, it can buy fine

2021-02-15 20:17:56,164,164 INFO CTSIBNB: Buy order filled... Try sell...
Message : Filter failure: PRICE_FILTER

im running like this:
python3 trader.py --symbol CTSIBNB --quantity 100 --profit 0.6  --debug
