### ISSUE TITLE
tries to sell after the sell was sucessful

### ISSUE THREAD

**Issue by Stauc** [yasinkuyu/binance-trader#116]
maybe it has to do with the partial fill, take a look:

![image](https://user-images.githubusercontent.com/2334869/35144220-9690b67a-fd0c-11e7-8453-a262089efb1c.png)

**Comment by Wrexen** [comment]
I have the same problem.

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/issues/102#issuecomment-358251258
