### ISSUE TITLE
Error filter failure: PRICE_FILTER

### ISSUE THREAD

**Issue by Technorocker** [yasinkuyu/binance-trader#120]
First off great and simple program, I'm just learning coding myself and find this wasnt too hard to read through and understand.

I got the program to start running but came across an error when it tries to make a move on the market.
It will run fine checking prices then suddenly I started getting the Error: Filter failure: PRICE_FILTER

Does anyone know what caused this or have also came across this error?

![python bot error](https://user-images.githubusercontent.com/35610201/35166860-473f40ae-fd21-11e7-919c-cb650aa717b2.PNG)

**Comment by Technorocker** [comment]
So doing a bit or reading and research to hopefully solve my own issue. Is this cause of maybe my profit margin being to low or my quantity being to low on the sell side? Found the link to the Binance api docs but am not quite understanding what its telling me

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/issues?utf8=%E2%9C%93&q=PRICE_FILTER

**Comment by Technorocker** [comment]
Thanks for the links

**Comment by markus27183** [comment]
Probably u r specifying the price to too high a precision
