### ISSUE TITLE
Import Tools.py Error

### ISSUE THREAD

**Issue by Technorocker** [yasinkuyu/binance-trader#122]
Call me noob but I cant seem to find a spot to comment on forks of this software.

Both wespeakcrypto and devx updated programs both throw the same error when I try to start bot about not being able to import the tools from tools.py

![python bot error](https://user-images.githubusercontent.com/35610201/35175668-c6660aea-fd42-11e7-919e-314f6125ee2d.PNG)

Sorry if this is an obvious mistake on my part

**Comment by Technorocker** [comment]
Caught the problem... using Devx's fork

in your Tools.py your class name isn't capitalized. Correct the tool to Tools and it starts up fine

**Comment by yasinkuyu** [comment]
My fault. I'm fixing now.

**Comment by Technorocker** [comment]
No problem. I was scratching my head wondering why I couldnt see anything wrong earlier. Thanks again for the program :) 

Since your around. Like I said im just learning coding and can somewhat understand but its still mildly German to me at this point. When I run the program I'm watching the numbers and from what I understand its:
Binance price || My willing price || my sell price || orderbook bid prices || orderbook buy prices||

is this correct?

cause I'm watching the screen and even with a small profit margin of 0.5 the buy is above the market price(not by much but still) and the sell is way away like 5 or 6 dollars(using ETH/USDT). So Id be buying for more than value and never selling unless price took a spike.

![bot info](https://user-images.githubusercontent.com/35610201/35176282-0f00ccba-fd46-11e7-90a2-0b80d6495450.PNG)

Ive also tried using the buy price and sell price in the range mode thinking it was a difference of the price by what value I put in. So I entered 0.50 to jump in and out of just for trial but it actually sets my ask and sell price to 50 cents when the price is 1014.00 is there a way to take price from check and just add that number to it? Im still soaking in the code so I cant really pin point where I would try and adjust the formula for the buy/sell option

Thanks for your help ahead of time

**Comment by Technorocker** [comment]
1 last edition to my last inquiry. When I set the range mode to buyprice and sellprice is that for a specific price firm? 
How can I adjust the buyprice to try and buy for XX price under current market... for example if ETH/USDT is at 1041.00 I want the bot to buy in at say 1040.00 then sell at 1042.00 or 1 dollar each way of current price. If that makes sense to you. Cause right now with profit set to 0.1 my offer price is still above market and sell price is many dollars above market.

![bot info](https://user-images.githubusercontent.com/35610201/35177216-cc924862-fd4b-11e7-92a7-935b000c9a94.PNG)

Give me a working bot that does that and I'd definitely be tipping out the devs for a simple working price skimmer lol :)
