### ISSUE TITLE
Order stuck in queue. 

### ISSUE THREAD

**Issue by Jagermeister56** [yasinkuyu/binance-trader#123]
![screen shot 2018-01-19 at 6 34 05 pm](https://user-images.githubusercontent.com/17785698/35176486-65d3026e-fd47-11e7-9e28-5b16ded9fa4c.png)

**Comment by elCapitanoh** [comment]
Have you used "git pull" to update? It should fix PRICE_FILTER errors and now the bot's smart enough to cancel buy orders if they aren't filled instantly.
