### ISSUE TITLE
Feature Request: Compounding Profits

### ISSUE THREAD

**Issue by elCapitanoh** [yasinkuyu/binance-trader#125]
Hey, could we have a feature (that can be toggled) which has the bot calculate the max amount to trade based on balance instead of statically setting a quantity? This would allow for significantly greater gains overtime.

To anyone who says it's very risky, yes, I understand; that's why I want it to be a parameter that can be toggled.

**Comment by WeSpeakCrypto** [comment]
@elCapitanoh  Amount option is already implemented in Devx and WeSpeakCrypto branch. Do you want to try it first before we add an option for max_amount? It would be safer if we make it stable first before using all of our balance during trade.
