### ISSUE TITLE
Docker run import 'Trading' error

### ISSUE THREAD

**Issue by ikuru9** [yasinkuyu/binance-trader#137]
Traceback (most recent call last):                                              
  File "./trader.py", line 9, in <module>                                       
    from Trading import Trading                                                 
ModuleNotFoundError: No module named 'Trading'

**Comment by siutin** [comment]
1. Change Dockerfile to the following and then build it:
```
FROM python:3
ADD app/* /
ADD trader.py /
RUN pip install requests
CMD [ "python", "./trader.py" ]
```
2. Rename `./db/orders.sample.db` to `./db/orders.db`

3. Run in container with database mapping
```docker run -t -i -v $(pwd)/db/orders.db:/db/orders.db trader```

**Comment by kompots** [comment]
Go the same issue :(
