### ISSUE TITLE
UPDATED! STABILIZED! Topic: Auto coin picker?

### ISSUE THREAD

**Issue by WeSpeakCrypto** [yasinkuyu/binance-trader#141]
**Hi All,**

Recent update might be stable for now and can run for days (done tests myself).
You can check it out in [my forked repo](https://github.com/WeSpeakCrypto/binance-trader) or in [rebranched repo named WeSpeakCrypto](https://github.com/yasinkuyu/binance-trader/tree/WeSpeakCrypto).
Remember to read the Readme first because my wallets are there. Donations are welcome. :laughing: 

Now, if I am to create an option where the program picks a coin itself.
What should be the qualities it have to be picked?

  "priceChange": "-94.99999800",
  "priceChangePercent": "-95.960",
  "weightedAvgPrice": "0.29628482",
  "prevClosePrice": "0.10002000",
  "lastPrice": "4.00000200",
  "lastQty": "200.00000000",
  "bidPrice": "4.00000000",
  "askPrice": "4.00000200",
  "openPrice": "99.00000000",
  "highPrice": "100.00000000",
  "lowPrice": "0.10000000",
  "volume": "8913.30000000",
  "quoteVolume": "15.30000000",
  "fristId": 28385,   // First tradeId
  "lastId": 28460,    // Last tradeId
  "count": 76         // Trade count

It can be combination of those. I need experienced people here to please help us out.
Thanks!

I might not going to make changes for this week, so many things to do at work.
So for the meantime, please keep this thread alive and flowing with information. :smile:

**Comment by nealgentry** [comment]
thank you so much or all the work you both have put into this project! I'm donating my first weeks profits to the both of you!  i can finally erase my shitty custom build 'learned python' this week .  I've been trading for 6 months now as a hobby started with $20 now I'm over 4k with who knows how much I've spent. 

i would love to auto buy with weightedAvgPrice & Trade count, increasing or decreasing 'option%' in 'timespan' 


Just a Nifty simple idea. thanks guys!

**Comment by yasinkuyu** [comment]
Good idea. We can improve this tool even more. https://github.com/yasinkuyu/binance-trader/blob/b3dda624caac19b8d8ae5b8c095c36d29a5b8088/balance.py#L66

**Comment by ktenman** [comment]
Guys are you working on MACD implementation?  😀

**Comment by yasinkuyu** [comment]
@ktenman yeap

**Comment by mahatatti** [comment]
@WeSpeakCrypto I ran the forked repo for few minutes and it made some weird transactions.
Is the default setting broken or am i missing something 
This is what i set .
python trader.py -symbol LTCBTC -profit 0.3

![screenshot_20180121-182729](https://user-images.githubusercontent.com/35596690/35202856-f3766d70-fed9-11e7-9809-bd739b89be29.png)

**Comment by WeSpeakCrypto** [comment]
@nealgentry You're welcome. Suggestion noted. :smile: 

@yasinkuyu Do we have to put this kind of implementation in that file? Are you doing the MACD part there?

@ktenman How about EMA? Can you share your knowledge about the chart tools you know here?

@mahatatti Sorry for that. --increasing (for buy price) and --decreasing (for sell price) default value is 0.2% meaning your buy price will increase 0.2% and sell price will decrease by 0.2% thus turning your profit of 0.3% to -0.1% minus fee -0.15% or near that. Fix it by manipulating --increasing and --decreasing or just set bot to 0.

**Comment by nealgentry** [comment]
OK i've switched from my wi-fi connection to a gigabit wired connection and it stabilized everything and bot performs better now...  must be some kind of latency issues ...  

So run on wired connection.

running 2 instances on different currency pares..  will be switching to 4 instances tomorrow  if all goes well. so far USDT has 5 winning trades and ETH has 20 winning trade with 100% stability.
![screenshot from 2018-01-22 00-04-57](https://user-images.githubusercontent.com/34993553/35207415-7daf31f6-ff08-11e7-8254-1cc3103feb7f.png)

**Comment by TheFitzZZ** [comment]
@nealgentry thanks for sharing your experience! Cool to see you having winning trades - what about losing trades? Are in in the green overall?

**Comment by nealgentry** [comment]
no losing trades.  yet...

**Comment by nealgentry** [comment]
$44 in profit over all last night while i was sleeping.   sending to @yasinkuyu & WeSpeakCrypto

**Comment by TheFitzZZ** [comment]
@nealgentry could you please share your complete parameters please? I lost a few bucks today (nothing bad) and wanna see where I differ.

**Comment by walruzperil** [comment]
@nealgentry You trade BTCUSDT and ETHUSDT?

**Comment by mahatatti** [comment]
@nealgentry Yeah it would be helpful if you could share the parameters and the symbols . The thing is for us,  we are seeing both upswings and downtrends sometimes. I gained a bit yesterday but lost fews bucks yesterday night

**Comment by walruzperil** [comment]
@WeSpeakCrypto, some times error and quit... Order was buy, but no set sell order..
Buy order filled... Try sell...
Sell order create id: 5257145
Not sold after 5 seconds, wait 5 more seconds...
Profit loss, called order, 5257145
m: Filter failure: PRICE_FILTER
Traceback (most recent call last):
  File "trader.py", line 46, in <module>
    t.run()
  File "./app/Trading.py", line 494, in run
    self.action(symbol)
  File "./app/Trading.py", line 378, in action
    self.sell(symbol, quantity, self.order_id, profitableSellingPrice, lastPrice)
  File "./app/Trading.py", line 159, in sell
    self.stop(symbol, quantity, sell_id, sell_price)
  File "./app/Trading.py", line 216, in stop
    sell_id = sello['orderId']
KeyError: 'orderId'

**Comment by VasTShadowZz** [comment]
fell free to join the discord for this project and add it into the suggestions! https://discord.gg/Xn7Fgek

**Comment by arielmoraes** [comment]
@nealgentry , how much did you invest to get a $44 profit?

**Comment by linhndd** [comment]
How to using it ? I think it auto choice coin and auto trade for me ? or I need choose coin and running  be like yasinkuyu brand ?

**Comment by linhndd** [comment]
I running it and it always buy but never sell again :|

**Comment by Maathouse** [comment]
Hi!

At first I was to thank you for al the work you've done!

I'm running the newest version but encounter a problem: whenever I put a stop-loss limit at like 5%, it sells the position when it's down like 1%. I've tried '50' as well but then it runs into an error. Is there a way to fix the inputs so it sells only when it's down 5%?

**Comment by Maathouse** [comment]
Hi!

The bot was working for 3 days. Currently ut doesn't recognize the sell orders anymore and gives an 'FAILED SERVER REQUEST' error. It creates an sell order but does not cancel it anymore automatically. It this the Binance API facing problems?

**Comment by nealgentry** [comment]
The binance server was having issues...

**Comment by Maathouse** [comment]
Changed the url to us.binance.com but its still crashing after 5 minutes or so. Others face this issue as well?
