### ISSUE TITLE
Filter Failure: Min_Notional

### ISSUE THREAD

**Issue by TexGoose** [yasinkuyu/binance-trader#15]
![capture](https://user-images.githubusercontent.com/34754964/34280597-782f795e-e67e-11e7-8a7d-f1bb1bcbdb16.PNG)

**Comment by bestlinkXx** [comment]
Hello, 

you don't take sufficient quantity with your symbol price to reach to minimum on Binance (0.001)
Just fix this value.

**Comment by yasinkuyu** [comment]
--quantity 3 increase

Ex: trader.py --quantity 10
