### ISSUE TITLE
NO trades but no errors from bot

### ISSUE THREAD

**Issue by RedRum69** [yasinkuyu/binance-trader#150]
HI there,

I can't seem to get this working. Bot seems to work on the CMD, no errors. But binance doesn't show any trades.

Using windows.

![image](https://user-images.githubusercontent.com/8095425/35243530-1e67c548-ffb5-11e7-867d-89f2d2d65e43.png)

**Comment by kfiresmith** [comment]
You need to:
1.  Be patient and let it run potentially for hours
2.  Try a lower target profit

**Comment by RedRum69** [comment]
odd, I have run it all night, not visible errors and still no trades.

I have lowered the target priory to going to sleep.

**Comment by yasinkuyu** [comment]
1.3 difficult to get caught in profit steady processing. Mostly there is a high profit margin during the pump. Try a lower target profit --profit .5 or --profit .8
