### ISSUE TITLE
Price buyP error?

### ISSUE THREAD

**Issue by Technorocker** [yasinkuyu/binance-trader#151]
Can someone please tell me if I'm reading this wrong? 
![bot error](https://user-images.githubusercontent.com/35610201/35251690-54be4244-ffaa-11e7-8eaa-25604539eb95.PNG)

the first price is the exchange price correct?
the second part is Buyp which is what the bot wants to buy at correct?
then sellp is what the bot would sell at...

everytime I run the bot I always see the buyp price above the market price. Am I setting up the params wrong?

**Comment by yasinkuyu** [comment]
There is no problem. It was like everything.
Ask +1 (--increasing XX) Buy price. 
It increases the price for the first purchase.
