### ISSUE TITLE
Whenever a buy order is filled, Filter failure happens.. Endlessly...

### ISSUE THREAD

**Issue by lhjk** [yasinkuyu/binance-trader#157]
I've used below settings for this log, but tried with a few other settings as well and they are all giving the same failure.

python trader.py --symbol BTCUSDT --profit 0.3

price:11196.00000000 buyp:11215.51000000 sellp:11249.14650000-bid:11215.50000000 ask:11219.96000000 spread:0.04
price:11190.08000000 buyp:11186.72000000 sellp:11220.27013000-bid:11186.71000000 ask:11219.96000000 spread:0.30
price:11200.00000000 buyp:11200.01000000 sellp:11233.60000000-bid:11200.00000000 ask:11200.17000000 spread:0.00
price:11181.76000000 buyp:11181.78000000 sellp:11215.31531000-bid:11181.77000000 ask:11219.78000000 spread:0.34
Buy order created id:27475850, q:0.00009800, p:11181.78000000
Buy order filled... Try sell...
m: Filter failure: PRICE_FILTER
Buy order filled... Try sell...
m: Filter failure: PRICE_FILTER
Buy order filled... Try sell...
m: Filter failure: PRICE_FILTER
Buy order filled... Try sell...
m: Filter failure: PRICE_FILTER
Buy order filled... Try sell...
m: Filter failure: PRICE_FILTER
^CTraceback (most recent call last):
  File "trader.py", line 45, in <module>
    t.run()
  File "./app/Trading.py", line 520, in run
    time.sleep(self.wait_time - (endTime - startTime))
KeyboardInterrupt

**Comment by VasTShadowZz** [comment]
same, it is happening to all of us.the bot is still running just with the errors.

**Comment by lhjk** [comment]
Oh, okay.
So the bot is still running.
Then I guess I should just wait for an update.
Thanks.
