### ISSUE TITLE
invalid symbol

### ISSUE THREAD

**Issue by scottiesan** [yasinkuyu/binance-trader#158]
Invalid symbol, please try again...
xxxxxxxx$ python trader.py --symbol XVGBTC 
@yasinkuyu, 2018
Auto Trading for Binance.com. --symbol: XVGBTC

... 

Invalid symbol, please try again...

I am just testing to see if it works... any idea?  This is the example command on git.  

Thanks!

**Comment by scottiesan** [comment]
This was caused by my vpn block the request.

**Comment by mann788** [comment]
@scottiesan i'm having the same issue. how did you solved it?
