### ISSUE TITLE
KeyError: 'lastPrice'

### ISSUE THREAD

**Issue by JordySteyaert** [yasinkuyu/binance-trader#16]
%0.5 profit scanning for IOTAWTC
Traceback (most recent call last):
  File "trader.py", line 210, in <module>
    main()
  File "trader.py", line 203, in main
    action(symbol)
  File "trader.py", line 129, in action
    lastPrice = get_ticker(symbol)
  File "trader.py", line 113, in get_ticker
    return float(ret["lastPrice"])
KeyError: 'lastPrice'

**Comment by yasinkuyu** [comment]
Try IOTABTC

**Comment by Foof811** [comment]
About how long does it take before it starts buying and selling for IOTABTC?

**Comment by yasinkuyu** [comment]
For example, if IOTABTC is looking for 1.3% profit, the order will be opened when it is found.
If the order is completed, a profit of 1.3% is sought for sale.
