### ISSUE TITLE
m: Signature for this request is not valid.

### ISSUE THREAD

**Issue by VasTShadowZz** [yasinkuyu/binance-trader#160]
price:0.00000885 buyp:0.00000887 sellp:0.00000889-bid:0.00000885 ask:0.00000886
price:0.00000885 buyp:0.00000887 sellp:0.00000889-bid:0.00000885 ask:0.00000886
price:0.00000885 buyp:0.00000887 sellp:0.00000889-bid:0.00000885 ask:0.00000886
price:0.00000885 buyp:0.00000887 sellp:0.00000889-bid:0.00000885 ask:0.00000886
price:0.00000885 buyp:0.00000887 sellp:0.00000889-bid:0.00000885 ask:0.00000886
price:0.00000885 buyp:0.00000886 sellp:0.00000888-bid:0.00000884 ask:0.00000885
price:0.00000885 buyp:0.00000886 sellp:0.00000888-bid:0.00000884 ask:0.00000885
price:0.00000885 buyp:0.00000886 sellp:0.00000888-bid:0.00000884 ask:0.00000885
price:0.00000884 buyp:0.00000886 sellp:0.00000888-bid:0.00000884 ask:0.00000885
price:0.00000884 buyp:0.00000886 sellp:0.00000888-bid:0.00000884 ask:0.00000885
price:0.00000884 buyp:0.00000886 sellp:0.00000888-bid:0.00000884 ask:0.00000885
price:0.00000884 buyp:0.00000886 sellp:0.00000888-bid:0.00000884 ask:0.00000885
price:0.00000885 buyp:0.00000882 sellp:0.00000884-bid:0.00000880 ask:0.00000885
m: Signature for this request is not valid.
bl: 'orderId'
price:0.00000884 buyp:0.00000882 sellp:0.00000884-bid:0.00000880 ask:0.00000884
price:0.00000884 buyp:0.00000882 sellp:0.00000884-bid:0.00000880 ask:0.00000885

weird

**Comment by SoftMandar** [comment]
Anyone who solved this issue ? i still encounter it ,any solution?

**Comment by ykartal** [comment]
@SoftMandar  _sign method updated and I think the problem is solved.

**Comment by PCPisChill** [comment]
Just downloaded the latest version and I get the same error, tried generating a new key too:

```
0.01% profit scanning for 

Between Ask and Bid 0.01% profit hunting
buyp : BuyPrice  (Bid+ --increasing 0.00000001)
sellp: SellPrice (Bid- --decreasing 0.00000001)
...

price:0.00005692 buyp:0.00005693 sellp:0.00005693-bid:0.00005692 ask:0.00005694
spread:0.04
m: Signature for this request is not valid.
price:0.00005692 buyp:0.00005693 sellp:0.00005693-bid:0.00005692 ask:0.00005694
spread:0.04
m: Signature for this request is not valid.
price:0.00005692 buyp:0.00005693 sellp:0.00005693-bid:0.00005692 ask:0.00005694
spread:0.04
m: Signature for this request is not valid.
price:0.00005694 buyp:0.00005693 sellp:0.00005693-bid:0.00005692 ask:0.00005695
spread:0.05
m: Signature for this request is not valid.
price:0.00005694 buyp:0.00005693 sellp:0.00005693-bid:0.00005692 ask:0.00005695
spread:0.0511

**Comment by ykartal** [comment]
Please track this issue from [here](https://github.com/yasinkuyu/binance-trader/pull/192#issuecomment-365767256):
