### ISSUE TITLE
Orders.py is an Unessessary Module - Consolidate into BinanceAPI.py 

### ISSUE THREAD

**Issue by RGAlexander216** [yasinkuyu/binance-trader#167]
Almost all the methods essentially are only functioning to print a message. this can cause some issue with docstrings in some IDEs as it makes the docstring inaccessible.

**Comment by yasinkuyu** [comment]
I actually thought of database connections in orders.py, but there was no opportunity to complete it. Can be combined with BinanceAPI.py
