### ISSUE TITLE
What it is ? Invalid api-key, IP, or permissions for action

### ISSUE THREAD

**Issue by sergceh** [yasinkuyu/binance-trader#168]
Hi, can't run python script in windows. 
![2018-01-26_11-49-35](https://user-images.githubusercontent.com/35559490/35431895-61997c4e-028f-11e8-82cf-e42b491084bd.png)

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/wiki/Windows-Installation-for-Binance-Trader

**Comment by sergceh** [comment]
Thank you

**Comment by sergceh** [comment]
What is not right, the api correct
![default](https://user-images.githubusercontent.com/35559490/35437099-07fdae5e-02a2-11e8-92c7-9a581ec31f97.jpg)

**Comment by yasinkuyu** [comment]
Go API Center, https://www.binance.com/userCenter/createApi.html

Create New Key
 [✓] Read Info [✓] Enable Trading [X] Enable Withdrawals 
Rename _**config.sample.py**_ to **config.py** / orders.sample.db to orders.db

Get an API and Secret Key, insert into **config.py**

 API key for account access
 api_key = ''
 Secret key for account access
 api_secret = ''

**Comment by sergceh** [comment]
That's exactly what I did. At first I incorrectly wrote in quotes ''. The bot did not start. But now I've sort of rightly inscribed, the scanning is on, but with such a record between the lines.

**Comment by sergceh** [comment]
Do you need to leave quotation marks? Both at the end? Or clean? Sorry, for the stupid questions.

**Comment by elysium-12** [comment]
They are single quotes, so you need to add your keys in between them:
API key for account access
api_key = 'XXXXXXXXXX'
Secret key for account access
api_secret = 'XXXXXXXX'

**Comment by Ben21k** [comment]
My case was IP access problem. Problem resolved once I updated my IP address onto my API key in binance webpage.

**Comment by nasirahmad06** [comment]
I have same case. but the problem just if I make sell order on marketname WPCBTC. for another marketname not problem, it can sell order. but just WPCBTC my bot can't create order. how can i solved this?
