### ISSUE TITLE
Connexion Aborted : Name or service not known

### ISSUE THREAD

**Issue by AxelDeneu** [yasinkuyu/binance-trader#174]
When I run my script for about a day, if it stop running, this is 90% of the time the error i get. I don't even know what does it means... Does anyone had the same issue ?
<img width="815" alt="capture d ecran 2018-01-28 a 23 38 14" src="https://user-images.githubusercontent.com/22771331/35488171-a370db7a-0484-11e8-97e8-0fecf21d27a6.png">

**Comment by AxelDeneu** [comment]
Am i the only one who had this recurrent bug ?

**Comment by ykartal** [comment]
İt seems the problem is about your network, DNS or internet connection.

**Comment by AxelDeneu** [comment]
That's quite strange, the bot is on an Digital Ocean Droplet, bandwidth is more than ok and the ping too
![capture du 2018-02-21 11-30-13](https://user-images.githubusercontent.com/22771331/36475447-f9b5bc8e-16fa-11e8-9389-3c9f8b280838.png)

**Comment by ykartal** [comment]
Did you check your firewall or used DNS? 
Your computer or network firewall may block connection sometimes later.

**Comment by yasinkuyu** [comment]
Looks like a temporary connection problem. What's the latest situation?
