### ISSUE TITLE
bl: no such table: orders 

### ISSUE THREAD

**Issue by awgal** [yasinkuyu/binance-trader#176]
I have renamed it but still keep getting the "bl: no such table: orders" and just keep buying without placing sell orders... 

<img width="556" alt="screen shot 2018-01-29 at 6 33 51 pm" src="https://user-images.githubusercontent.com/32092730/35515627-22d475d6-0523-11e8-9335-e4172b59a84c.png">
<img width="896" alt="screen shot 2018-01-29 at 6 34 22 pm" src="https://user-images.githubusercontent.com/32092730/35515628-230bd9fe-0523-11e8-8590-3796e590e608.png">

**Comment by PlayboySatoshi** [comment]
Same here. Is there a solution to this?

**Comment by PlayboySatoshi** [comment]
Nevermind. I found the answer. It`s here https://github.com/yasinkuyu/binance-trader/issues/92

**Comment by yasinkuyu** [comment]
Rename config.sample.py to config.py / orders.sample.db to orders.db
