### ISSUE TITLE
"bl: no such table: orders" & "account has insufficient balance" (all buy, no sell)

### ISSUE THREAD

**Issue by TonoIdo** [yasinkuyu/binance-trader#177]
I download the current trader, run it, and I get the following error:
![error 1](https://user-images.githubusercontent.com/31077387/35525591-e01b4f4a-051c-11e8-8a9f-57cb8fbdec1c.png)

I thought I would work around it by moving the contents of the '/app' folder out to the main folder, then going into trader.py and changing `sys.path.insert(0, './app') from Trading import Trading` to `sys.path.insert(0, './') from Trading import Trading` 
But then I get this error:
![error 2](https://user-images.githubusercontent.com/31077387/35525603-e5a907c2-051c-11e8-8661-6e5340459b38.png)

So I move the orders.db file out into the main folder, go into database.py, and change `'../db/orders.db')
` to `'../orders.db'`. 

Then the program runs, but I get `bl: no order tables` whenever it tries to buy and `account has insufficient balance` whenever it tries to sell. 
![error 3](https://user-images.githubusercontent.com/31077387/35528984-7d9f3e48-0527-11e8-9521-70ff1c35986a.png)
On the actual binance account, the buy orders go through fine, but then the program nevers sells. Also I noticed an Orders.db file was created out in the downloads folder, but it then never gets used/edited.

**Comment by rickdeaconx** [comment]
Try to buy some BNB to do the transactions or disable that feature in Binance account settings

**Comment by TonoIdo** [comment]
@rickdeaconx Tried both. No effect. I'm pretty sure this is some issue with those file paths and the folders. 
It's like the program can't access files outside the base folder. So anything in /app or /db is off limits. And consolidating the files into one big folder generates issues.

**Comment by rickdeaconx** [comment]
Copying the files change R/W permissions?

**Comment by TonoIdo** [comment]
Just tried Git to clone the repo rather than downloading and extracting a .zip. Now the program runs without me restructuring the files/folders. But I get the same errors. This time with `bl: orderid` following the `insufficient balance`:
![screen shot 2018-01-29 at 6 17 13 pm](https://user-images.githubusercontent.com/31077387/35539711-be525e9a-0520-11e8-83e3-52da5133dad6.png)

**Comment by rickdeaconx** [comment]
BNB fixed that error for me, sorry.

**Comment by TonoIdo** [comment]
Wait, wait, I'm an idiot. After the git clone, I forgot to rename orders.sample.db to orders.db. I've done that and the trader finally seems to be running fine with no issues. Praise be to @rickdeaconx! I shall sacrifice a goat in your name
