### ISSUE TITLE
No module names 'Trading' when I run in docker...

### ISSUE THREAD

**Issue by dogepng** [yasinkuyu/binance-trader#181]
Hi, whenever I type `docker run trader` it always come with the message:

$ docker run trader
Traceback (most recent call last):
  File "./trader.py", line 9, in <module>
    from Trading import Trading
ModuleNotFoundError: No module named 'Trading'

Can anyone help me out?

![image](https://user-images.githubusercontent.com/35969281/35638468-1b69deb6-06af-11e8-98cb-12cc3f14f1e1.png)
![image](https://user-images.githubusercontent.com/35969281/35638516-36a4e45a-06af-11e8-8608-e460c6ffbf3c.png)

![image](https://user-images.githubusercontent.com/35969281/35638540-45e1af16-06af-11e8-8248-acf3fc05a28f.png)

**Comment by matiller** [comment]
Same problem... On ubuntu 16.04...

**Comment by sweetpythoncode** [comment]
touch __init__.py in app dir

**Comment by matiller** [comment]
Sorry i didn’t get it, how do you mean it? Thanks for reply... ( i am total noob in these things)

**Comment by matiller** [comment]
I tried to touch init.py in app dir, I let it clear and it didn’t work...

**Comment by matiller** [comment]
Btw I’ve tried __init__.py too
