### ISSUE TITLE
selling at a loss

### ISSUE THREAD

**Issue by elysium-12** [yasinkuyu/binance-trader#183]
![image](https://user-images.githubusercontent.com/23282747/35714261-aa12fa0e-0799-11e8-9cb2-cce12ca16228.png)
Selling at  a loss with the following settings:
```
python trader.py --symbol PIVXBTC --profit 1 
```

**Comment by walker1371** [comment]
add parameter: stop_loss 0

**Comment by elysium-12** [comment]
thanks I'll that
