### ISSUE TITLE
Price_Filter (known issue with unknown solution)

### ISSUE THREAD

**Issue by PlayboySatoshi** [yasinkuyu/binance-trader#185]
I think I`ve read all of the posts about the Price_Filter issue during sell. But I still couldn`t figure out what is the perfect solution for this as I tried pretty much everything I read so far.

I keep getting

Buy order filled... Try sell
m: Filter failure: PRICE_FILTER

Sometimes it gives this error after creating few sell orders

I`m doing LTCBTC so the prices are 0.014754 or so. It uses only 6 digits after the dot . 

I tried 
--increasing 0.000001
--increasing 0.0001 -- decreasing 0.0001
--increasing 0.001 --decreasing 0.001

Nothing worked... Please help

**Comment by nealgentry** [comment]
Line 140  BinanceAPI.py

def _format(self, price):
        if float(price) < 0.1:
            return "{:.6f}".format(price)        #using 6 digits
        else:
            return "{:.6f}".format(price)   # or 6 digits

**Comment by PlayboySatoshi** [comment]
I don`t get it. Do you mean I should replace the 140 and 141 with this? or are you just showing what is the problem?

Could you tell me step by step how to fix it please? I`m still a Newbie here

**Comment by PlayboySatoshi** [comment]
It keps giving syntax errors so I just changed the 8f to 6f and saved it like that and also noticed that I forgot to install the requirements. So It seems to be working for now. Thank you very much Mr. :)
