### ISSUE TITLE
If your script doesn't run due to Binance Website's issues

### ISSUE THREAD

**Issue by AxelDeneu** [yasinkuyu/binance-trader#189]
If for some reason your script doesn't run as expected (see the screenshot below, bot does nothing), freezing or crashing. It's probably due to the issues of the Binance Website.
![image](https://user-images.githubusercontent.com/22771331/36023401-989d442a-0d8c-11e8-8a89-434ca6a12ec9.png)
Atm it should be solved. But for DDoS reason the "www" version of their website is still unaccessible some moments.
To solve that you can :
 - Wait until it's ok
 - Temporarly modify code :
In "app/BinanceAPI.py", modify the "BASE_URL" : 
![image](https://user-images.githubusercontent.com/22771331/36023448-c27d03ca-0d8c-11e8-932d-c40ea233578a.png)
To : 
![image](https://user-images.githubusercontent.com/22771331/36023470-e1a25246-0d8c-11e8-8848-6b69be3ef144.png)
And that's it !
It should run as expected.

Remember that this is a temporary fix and i'm not responsible in any resulting bug.

If it solved the issue for you, don't hesitate to donate to @yasinkuyu via his wallet, and to me if you're rich ;) : 
ETH : 0xa4917d09a1a6f038116684a6cca461674412987b

**Comment by Plarkass** [comment]
I test it and doesn't work

**Comment by AxelDeneu** [comment]
Can you show me the app/BinanceAPI file ?
What does the script return ?

**Comment by Plarkass** [comment]
Sorry, my bad it works

**Comment by walker1371** [comment]
Tried both kr. and us. not working.

Bot is not functional anymore for me, since www.binance.com is not responding.

**Comment by AxelDeneu** [comment]
@walker1371 That’s strange, mine is running since yesterday with us. 
What does the bot return ?
Btw www.binance.com is working again, you should try to revert the modification

**Comment by walker1371** [comment]
Everything seems normal now. Desktop app, main domain, and scripts works.

**Comment by AxelDeneu** [comment]
Nice !
