### ISSUE TITLE
Keyerror: 'lastPrice'

### ISSUE THREAD

**Issue by Maathouse** [yasinkuyu/binance-trader#190]
Hi,

I'm getting the following error, seemingly at random. Occurs more often when I run multiple bots. If it happens, all bots crash at once.

Traceback (most recent call last):
 line 51, in <module>
    t.run()
  File "./app\Trading.py", line 494, in run
    self.action(symbol)
  File "./app\Trading.py", line 302, in action
    lastPrice = float(ticker['lastPrice'])
KeyError: 'lastPrice'

Any suggestions?

Thanks in advance!

**Comment by DVenerM** [comment]
Message from the server when this error occurs:
{'code': -1003, 'msg': 'Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.'}
What to do next I do not know.

**Comment by Maathouse** [comment]
Ah oke. Currently it does one request per 0.7 seconds with default settings right? Where did you get that error message?

**Comment by DVenerM** [comment]
Yes I put 1, get better

**Comment by yasinkuyu** [comment]
Looks like a temporary connection problem. What's the latest situation?

**Comment by Maathouse** [comment]
I adjusted the request time to 1.5sec. Never got the error afterwards.

**Comment by Yehmingzhu** [comment]
hey I cant figure it out what do i do!!?
