### ISSUE TITLE
what is means  "bl  no such tables: orders "?

### ISSUE THREAD

**Issue by RO360** [yasinkuyu/binance-trader#191]
![bl](https://user-images.githubusercontent.com/30150663/36100325-d3824d36-1040-11e8-8505-b0f251cb7dd0.png)

I set profit 0.57   for VIBBTC.

**Comment by RO360** [comment]
The app can buy but no sell ,  :(

**Comment by nilamoromete** [comment]
In db rename orders.sample.db to orders.db
