### ISSUE TITLE
Cant run the project -  unable to open database file

### ISSUE THREAD

**Issue by HappyHidra** [yasinkuyu/binance-trader#195]
Python 3.6, requests module installed. When I am trying to run trader.py appears this error:

  File "C:\Trader\Database.py", line 9, in <module>
    conn = sqlite3.connect(path, check_same_thread = False)
sqlite3.OperationalError: unable to open database file

**Comment by Maathouse** [comment]
Did you already download the sql part to run the code? I've found it on the internet how to install.

**Comment by HappyHidra** [comment]
Nope, It would be great if you`ll give me a link where you found this information, thanks!
