### ISSUE TITLE
Placing 2 orders 

### ISSUE THREAD

**Issue by HappyHidra** [yasinkuyu/binance-trader#198]
Hey everyone, bot is placing 2 buy orders, after proceed it sells both orders, and try to sell more, but balance is 0. It dont stop. 
How can I set order limits to 1? it would be like buy-sell-buy-sell and etc.

**Comment by Exeluzz** [comment]
Hello, i have the same issue i search for solution but never found ...

if you closed this issue, can you tell me who did you resolve this ?

Sry for my bad English vocabulary and grammar
