### ISSUE TITLE
TypeError: function takes exactly 1 argument (3 given)

### ISSUE THREAD

**Issue by dotrader** [yasinkuyu/binance-trader#2]
Hi thanks for the great code, bot works but when it buyes a share gives error and exits code, i start again but same, allways it buyes but couln't sell anyway for crashing.

i make test for BNBETH

```
do@dotrader:~/Downloads/binance-trader-master$ python trader.py
@yasinkuyu, 2017
Auto Trading for Binance.com (Beta). Enter your symbol. Ex: IOTABTC
BNBETH
%1.3 profit for scanning BNBETH

price:0.00840000 buyp:0.00810913 sellp:0.00819744-bid:0.00810903 ask:0.00819754 BTC:$19508.1

price:0.00840000 buyp:0.00810913 sellp:0.00819744-bid:0.00810903 ask:0.00819754 BTC:$19478.5

price:0.00840000 buyp:0.00810913 sellp:0.00819744-bid:0.00810903 ask:0.00819754 BTC:$19503.3

price:0.00840000 buyp:0.00810913 sellp:0.00819744-bid:0.00810903 ask:0.00819754 BTC:$19482.0

price:0.00842334 buyp:0.00810913 sellp:0.00819990-bid:0.00810903 ask:0.00820000 BTC:$19480.0

price:0.00842334 buyp:0.00815010 sellp:0.00819990-bid:0.00815000 ask:0.00820000 BTC:$19480.0

price:0.00830675 buyp:0.00815010 sellp:0.00819990-bid:0.00815000 ask:0.00820000 BTC:$19482.0

price:0.00830675 buyp:0.00815010 sellp:0.00819990-bid:0.00815000 ask:0.00820000 BTC:$19482.0

price:0.00842333 buyp:0.00815010 sellp:0.00823917-bid:0.00815000 ask:0.00823927 BTC:$19480.2

price:0.00842334 buyp:0.00815010 sellp:0.00823918-bid:0.00815000 ask:0.00823928 BTC:$19480.2

price:0.00842334 buyp:0.00810913 sellp:0.00823918-bid:0.00810903 ask:0.00823928 BTC:$19480.2
Traceback (most recent call last):
  File "trader.py", line 181, in <module>
    main()
  File "trader.py", line 174, in main
    action(symbol)
  File "trader.py", line 139, in action
    buy_limit(symbol, QUANTITY, buyPrice)
  File "trader.py", line 41, in buy_limit
    file.write(ORDER_ID,QUANTITY,buyPrice) 
TypeError: function takes exactly 1 argument (3 given)
```

**Comment by plgonzalezrx8** [comment]
Change the argument in line 41 to file.write("%s, %s, %s" % ORDER_ID,QUANTITY,buyPrice)

That worked for me.

**Comment by plgonzalezrx8** [comment]
Correction. It should be         file.write("%s, %s, %s" % (str(ORDER_ID),str(QUANTITY),str(buyPrice)))

**Comment by plgonzalezrx8** [comment]
Or you can just comment that line, it doesn't do anything other than log your orders.

**Comment by dotrader** [comment]
Thank you for quick reply, i solved it by your first code with adding double parentheses

`file.write("%s, %s, %s" % (ORDER_ID,QUANTITY,buyPrice))`

Then program gave that error;

```
Traceback (most recent call last):
  File "trader.py", line 181, in <module>
    main()
  File "trader.py", line 174, in main
    action(symbol)
  File "trader.py", line 139, in action
    buy_limit(symbol, QUANTITY, buyPrice)
  File "trader.py", line 49, in buy_limit
    print "Percentage of %s profit. Order created from %.8f. Profit: %.8f BTC" % (PROFIT, sellPrice, earnTotal)
NameError: global name 'sellPrice' is not defined
```

i comment "print "Percentage of %s profit..." line too, now it looks working.

**Comment by plgonzalezrx8** [comment]
On the action function in trader.py add the following lines right after the global variables.

    global lastPrice
    global sellPrice
    global earnTotal

**Comment by plgonzalezrx8** [comment]
Let me know how it performs for you. I'm not the main developer, but I've been working on this a lot today and will be submitting a pull request to see if the main dev like it.

**Comment by dotrader** [comment]
It performs well thanks again, i am not familiar with python, 

main developer made an update on the trader.py i download it, it performs well for now too.

I am closing this issue.

**Comment by kingadi111** [comment]
Guys can you help me figure this out . i keep getting this 

@yasinkuyu, 2017
Auto Trading for Binance.com (Beta). Enter your symbol. Ex: IOTABTC
POEBTC
%0.5 profit for scanning POEBTC
price:0.00000154 buyp:0.00000156 sellp:0.00000155-bid:0.00000155 ask:0.00000156 BTC:$18571.0
price:0.00000154 buyp:0.00000156 sellp:0.00000155-bid:0.00000155 ask:0.00000156 BTC:$18600.1
price:0.00000154 buyp:0.00000156 sellp:0.00000155-bid:0.00000155 ask:0.00000156 BTC:$18600.1
price:0.00000154 buyp:0.00000154 sellp:0.00000155-bid:0.00000153 ask:0.00000156 BTC:$18571.0
Error: Filter failure: MIN_NOTIONAL

Traceback (most recent call last):
  File "C:\bot\trader.py", line 188, in <module>
    main()
  File "C:\bot\trader.py", line 181, in main
    action(symbol)
  File "C:\bot\trader.py", line 143, in action
    ORDER_ID = buy_limit(symbol, QUANTITY, buyPrice)
  File "C:\bot\trader.py", line 37, in buy_limit
    errexit(ret['msg'])
  File "C:\bot\trader.py", line 108, in errexit
    exit(1)
  File "C:\Python27\lib\site.py", line 358, in __call__
    raise SystemExit(code)
SystemExit: 1
>>>

**Comment by kingadi111** [comment]
I Got a little past that by increasing the order amount now it hits me with this 

@yasinkuyu, 2017
Auto Trading for Binance.com (Beta). Enter your symbol. Ex: IOTABTC
POEBTC
%0.5 profit for scanning POEBTC
price:0.00000154 buyp:0.00000162 sellp:0.00000161-bid:0.00000161 ask:0.00000162 BTC:$18600.0
price:0.00000154 buyp:0.00000163 sellp:0.00000162-bid:0.00000162 ask:0.00000163 BTC:$18600.0
price:0.00000155 buyp:0.00000162 sellp:0.00000162-bid:0.00000161 ask:0.00000163 BTC:$18600.0
******************
Order Id: 618906
Percentage of 0.5 profit. Order created from 0.00000162. Profit: 0.00000000 BTC
#####################
Target sell price: 0.00000163 
Orders
Order: 618906: 0.000001	1000.000000	0.000000
Sales were made at 1.62e-06 price.
---------------------------------------------
Error: Account has insufficient balance for requested action.

Traceback (most recent call last):
  File "C:\bot\trader.py", line 188, in <module>
    main()
  File "C:\bot\trader.py", line 181, in main
    action(symbol)
  File "C:\bot\trader.py", line 160, in action
    sell_limit(symbol, QUANTITY, ORDER_ID)
  File "C:\bot\trader.py", line 84, in sell_limit
    errexit(ret['msg'])
  File "C:\bot\trader.py", line 108, in errexit
    exit(1)
  File "C:\Python27\lib\site.py", line 358, in __call__
    raise SystemExit(code)
SystemExit: 1
>>>

**Comment by yasinkuyu** [comment]
I will check.

**Comment by kingadi111** [comment]
i noticed that the order it was putting in was like this
even though the price was 169 satoshi , the bot tried to put a request in for 100 satoshi . then said insufficent balance even though i have a couple hundred free in there

12-18 17:12:18 | POE/BTC | Limit | Buy | 0.00000100 | 5,000 | 0.00% | 0.00500000 BTC
