### ISSUE TITLE
from Trading import Trading ImportError: No module named Trading

### ISSUE THREAD

**Issue by darubillah** [yasinkuyu/binance-trader#203]
When i run it, its giving following error, I tried running on pyton2 and python3 both also tried changing from Trading to from app.Trading but didnt resolve the issue.

<img width="563" alt="screen shot 2018-02-19 at 22 30 15" src="https://user-images.githubusercontent.com/5176243/36395970-7f9770a0-15c4-11e8-90f2-3b6aef0cf5bb.png">

**Comment by Exeluzz** [comment]
did you install dip dependencies ? with "dip install requests"

or juste check the PATH into the file

**Comment by darubillah** [comment]
you meant pip install requests right? if so yes I did,

and path seems fine I download package on desktop and run using following

python2 ~/Desktop/binance-trader-master/trader.py --symbol XVGBTC

also tried
python ~/Desktop/binance-trader-master/trader.py --symbol XVGBTC
python3 ~/Desktop/binance-trader-master/trader.py --symbol XVGBTC

**Comment by Exeluzz** [comment]
just test to run directly on the main folder.

command be like : python trader.py --symbol XVGBTC Cause if you oppenned trader.py you see this : sys.path.insert(0, "./app") 

and ./app contains the dependencies of the main program (trader.py) but it need to be lunch in the main folder

(sry for my bad english)

**Comment by darubillah** [comment]
thank you so much, after going inside the directory and running it, it worked.!

**Comment by Exeluzz** [comment]
you welcome ;)
