### ISSUE TITLE
Don't rebuy after sell 

### ISSUE THREAD

**Issue by Exeluzz** [yasinkuyu/binance-trader#206]
Hello :)

I have the last versions of files but update URLV3 into File API. 
When i launch the bot, it try to buy. whit the command : python trader.py --symbol ETCETH --profit 0.3

after he buy and try to sell OK.
But when the order are selled, the bot continue to sell the order like this : 

![image](https://user-images.githubusercontent.com/36524057/36451058-135593fa-1690-11e8-8eb0-0752218af669.png)

and if i restart the bot he run again and do the same.

Before, i was check different issues and i have found a other version of Trading.py but wih this i have min Notonial error and rewind to the original version.

Can you help me to understand why the bot doesn"t detect the order was selled ?

Thx 
best regards

**Comment by RedcoatAsher** [comment]
I am also getting this now :/  #frustrating

**Comment by Plarkass** [comment]
Filter failure: MIN_NOTIONAL https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule Filter failure: PRICE_FILTER https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md Timestamp for this request was 1000ms ahead of the server's time. https://github.com/yasinkuyu/binance-trader/issues

**Comment by Exeluzz** [comment]
Hello, 

Thx to reply and for this answer :) 

This work ok for me
