### ISSUE TITLE
Possible to check balance to sell remains

### ISSUE THREAD

**Issue by Maathouse** [yasinkuyu/binance-trader#217]
Hi!

Does someone know a part of code to check the balance of the currency you're trading? It happens to me sometimes that the bot is too late to cancel an buy order so it gets filled but it won't sell it again (due to server lag?)

What I would like to do:
- Check balance of currency
- Check whether the balance is >0.001 BTC to place an order
- Depending on this, place a limit or market order

I can figure out how to do the last two parts but I don't know how to check the current free balance. Any suggestions?

Thanks in advance!

Maathouse

**Comment by Maathouse** [comment]
Found it! I created by own balance checker from the get_balance code in 'Orders.py':

    #balance checker
    @staticmethod
    def get_balance_symbol(symbolbalance):
        try:

            balances = client.get_account()
            balances['balances'] = {item['asset']: item for item in balances['balances']}

            return balances['balances'][symbolbalance]['free']

        except Exception as e:
            print ('gb: %s' % (e))

To let it work, you should add symbolbalance as an parser argument in the trader.py. And add the variable 'symbolbalance'

Good luck for the ones who need it!

**Comment by pitxels** [comment]
@Maathouse Can you share the changes you did in trader.py ?  Thanks

**Comment by Maathouse** [comment]
I still have to do that but the above code can be used to check your balance. Also add:

parser.add_argument('--symbolbalance', type=str, help='Market Symbol (Ex: INS)', default=symbolbalance)

to the trader.py file and replace 'symbolbalance' by the symbol you want to check the balance from like INS as stated above.

**Comment by 78bash** [comment]
Could we please have this written up for a pull request by someone?
