### ISSUE TITLE
How Do I Fix This Startup Error?

### ISSUE THREAD

**Issue by rolflocher** [yasinkuyu/binance-trader#235]
trader.py --symbol XVGBTC
Traceback (most recent call last):
  File "C:\Users\XXXX XXXXXX\AppData\Local\Programs\Python\Python36-32\Scripts\trader.py", line 9, in <module>
    from Trading import Trading
ModuleNotFoundError: No module named 'Trading'

You helped someone else before with the same issue, but I do not understand what you mean by "run it on the main folder." How do I get my CMD to find the Trading Module?

**Comment by okeyzzang** [comment]
you can change the line as below.

sys.path.insert(0, 'c:/bot/binance-trader-master/app')

**Comment by rolflocher** [comment]
I fixed it using the Turkish Youtube video from another comment. I had to use the cd command to navigate my terminal to the bots folder on my desktop.
