### ISSUE TITLE
Error balance.py

### ISSUE THREAD

**Issue by CritSin** [yasinkuyu/binance-trader#247]
![adsiz](https://user-images.githubusercontent.com/19182149/40080815-d638c644-5894-11e8-9054-2a3c31570765.jpg)
please help me

**Comment by BatmanPDX** [comment]
try doing this, go to your binance trader bot directory in your shell program. and then type: easy_install requests

**Comment by BatmanPDX** [comment]
if you're running windows. you should download Git Bash, it's a shell program that features linux toolsets. 
https://git-scm.com/download/win
