### ISSUE TITLE
Error: Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.

### ISSUE THREAD

**Issue by xecov** [yasinkuyu/binance-trader#25]
Hello, 
i recive always this message and bot exit
Error: Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.

thanks

**Comment by ItsMates** [comment]
same for XVGBTC

**Comment by Foof811** [comment]
It happens periodically I noticed. That an Unknown order errors and insufficient fund errors.

**Comment by xecov** [comment]
-@Foof811same for me, and the bot only buy never sell it has buy verge all night long :) for my fortune now they are at +30%

**Comment by saumitrabhave** [comment]
Same as #29 , see if my workaround fixes the issue
