### ISSUE TITLE
Improve dockerfile

### ISSUE THREAD

**Issue by JunyuanZheng** [yasinkuyu/binance-trader#26]
https://github.com/yasinkuyu/binance-trader/blob/0e539acb5574a25babf81f2fc53fcee36a9dddd1/trader.py#L201

Hi, can I remove this line? I can improve the dockerfile so a user can deploy this trader easily.

**Comment by afoke** [comment]
Absolutely, you can improve the Dockerfile and submit a pull request.

The CLI was outputting error for the "name = raw_input()" portion of the code for me as well. I planned on looking into it later.

**Comment by JunyuanZheng** [comment]
Cool. Then I will do this. I will submit PR tonight.

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/56d1d2b1a8ea2b9a32f924a67f04c5c1f1bc2499
