### ISSUE TITLE
Assist with selling

### ISSUE THREAD

**Issue by TroyHGP** [yasinkuyu/binance-trader#268]
Yasinkuyu, thank you for your work on the project.

I have the bot running in range mode and it buys correctly but I cannot get the bot to make a sell. Any advice on how to make this happen? 

This is what prints in console after a successful buy:
`2019-12-22 14:57:59,412,412 INFO MTLBTC: MOde: range, Lastsk: 3.564e-05, Profit Sell Price 3.567e-05,`

And after I have ran out of Bitcoin it just repeats this message:
`2019-12-22 14:58:03,650,650 INFO MTLBTC: MOde: range, Lastsk: 3.564e-05, Profit Sell Price 3.567e-05,
Message : Account has insufficient balance for requested action.` 

Things I have tried to rectify-
-Making sure I have the coin I am trading from Bitcoin available in my account to cover a sell order
-Playing with commands such as --profit 0
-Making sure I am using BNB for fee's as I wasn't previously
-Waiting for buy side orders to cross my sell price in case it triggers a market sell order

As I said above it buys coins perfectly but I _cannot_ get the bot to make a sell no matter how much coin I have in the account or how closely I set the sells.

Thank you.

**Comment by williammikewhite** [comment]
Check that the database entries are getting written properly to orders.db. The bot must know what it has purchased in order to sell it.

**Comment by TroyHGP** [comment]
Thank you williammikewhite. I fixed the issue by doing a fresh clone of the repository so was unable to check your solution. Appreciate the response.
