### ISSUE TITLE
Api problem

### ISSUE THREAD

**Issue by mapulse** [yasinkuyu/binance-trader#277]
2020-06-24 19:22:29,759,759 WARNING SCBTC: Buy order fail (Not filled) Cancel order...
Message : Unknown order sent.
Message : Unknown order sent.
Message : Unknown order sent.

**Comment by mapulse** [comment]
and sometimes app stop itself

**Comment by aavesh1** [comment]
@mapulse  were you able to create even a single order?

**Comment by mapulse** [comment]
Binance api
