### ISSUE TITLE
IOTABTC

### ISSUE THREAD

**Issue by Foof811** [yasinkuyu/binance-trader#28]
I think one of the issues with the bot that conflicts with binance, is that when the bot says it buys 6 iota for instance, in reality, it's buying around 5.9, so when it goes to sell, it comes up with an insufficient funds error. We need to add a way for the bot to buy slightly more than it's setting out to buy, in order to actually put it at 6 iota instead of 5.9 or 5.8

**Comment by Foof811** [comment]
And binance only allows you to sell iota in whole numbers

**Comment by ekeloglu** [comment]
hello. if you have some bnb coin in your account, fees are paid from bnb coins not from coin itself.

for example if you buy 6 iotas and if you have 1 bnb coin in your account, then you buy 6 iota not 5.9 and fee is paid from bnb. after the trade, you will have 6 iotas and 0.98123 bnb coins in your account.
