### ISSUE TITLE
Not placing any order  , stuck at this

### ISSUE THREAD

**Issue by aavesh1** [yasinkuyu/binance-trader#283]
Started...
Trading Symbol: DOGEBTC
Buy Quantity: 4347.00000000
Stop-Loss Amount: 0
Profit Mode Options:
        Preferred Profit: 0.00%
        Buy Price : (Bid+ --increasing 0.00000001)
        Sell Price: (Ask- --decreasing 0.00000001)

**Comment by aavesh1** [comment]
No trades were opened.

**Comment by mvandrei** [comment]
the owner just updated his referral code link to work... but nothing on the app itself to work. I remember back a few years, I've left it over night and it simply lost me 7000 usd for malfunctioning. I don't recommend it. He is only after profit right now. Once you're signed up, and see that it's not working, you'll searhc for other bots or trade manually.... he is still the one referred you so...he wins

**Comment by yasinkuyu** [comment]
@mvandrei the charges you accused are stupid.
When the right coin is traded at the right time, it is possible to make a profit. I'm getting hundreds of positive messages about this. It's impossible to write a bot that will work 100% right on every trade and make a profit. Smart people do not distribute exchange bots for free. Sorry I did it!
