### ISSUE TITLE
Error: Filter failure: LOT_SIZE

### ISSUE THREAD

**Issue by HammadAWS** [yasinkuyu/binance-trader#31]
I have a bit modified my code but is giving an error, it would be great if someone can help...

sell_limit(symbol, 0.004995, 13658707)

def sell_limit(symbol, quantity, orderId):
global TEST_MODE
global ORDER_ID
global TARGET_PRICE
global TARGET_PROFITABLE_PRICE
global TARGET_PRICE

TARGET_PRICE = 0.206795

ret = client.sell_limit(symbol, quantity, TARGET_PRICE)

if 'msg' in ret:
    errexit(ret['msg'])
The code gives error on sell_limit() when I try to create order.

**Error: Filter failure: LOT_SIZE**

Can you suggest me what would be the reason?

**Comment by Foof811** [comment]
so you have it to buy at market price and sell at limit?

**Comment by HammadAWS** [comment]
Yes.
