### ISSUE TITLE
Bot no Buy/Sell

### ISSUE THREAD

**Issue by Usuario999** [yasinkuyu/binance-trader#37]
when it seems it is going to make order it tells me

Error : Filter failure: Price_Filter

Thank you for your work

**Comment by yasinkuyu** [comment]
Every coin can be different in --quantity.
Try increasing the quantity.

trader.py --quantity 20 --symbol XXXX

**Comment by Usuario999** [comment]
I'm testing with ETC quality-0.61 that goes well for that currency.
This is a while but when you go to make the purchase error

trader.py --quality 0.61 --symbol ETCBTC --profift 0.2 --wait_time 3 orderid 0

It should work

**Comment by Usuario999** [comment]
When you go to make the purchase the error comes out

**Comment by yasinkuyu** [comment]
I will check again.

---

<img width="754" src="https://user-images.githubusercontent.com/204635/34363276-bfb4b378-ea8b-11e7-8956-953638b59e1e.png">

https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

<img width="726"  src="https://user-images.githubusercontent.com/204635/34363225-46de5e5e-ea8b-11e7-8713-1730abd31ea7.png">

**Comment by Usuario999** [comment]
When you tell me, I'll make it work again

Thanks for a best job
