### ISSUE TITLE
Error: Filter failure: PRICE_FILTER

### ISSUE THREAD

**Issue by enginbyr** [yasinkuyu/binance-trader#41]
Merhaba Yasin,

Hesabımda 2.59149360 BNB var, LTC almak istiyorum. Aşağıdaki kodu çalıştırdığımda 

" Error: Filter failure: PRICE_FILTER " hatası almaktayım. Nasıl düzeltmem gerekiyor.

python2.7 trader.py --symbol LTCBNB --quantity 2 --profit 1.5

**Comment by yasinkuyu** [comment]
Selam. 

Bu hata için konu açılmıştı. Min sipariş miktarıyla ilgili bir sorun. Hafta sonu inceleyip döneceğim.

https://github.com/yasinkuyu/binance-trader/issues/37

**Comment by nealgentry** [comment]
I'm new to git-hub i signed up yesterday.  but if you get error PRICE_FILTER change the decimal places per Binance API   Example Change = :"Sales were made at %.8f price. " to "Sales were made at %.3f price." depending on the currency bianance does not accept 8 deciaml places...  some work with %.3f  or %.2f or %.4f...

**Comment by det-peralta** [comment]
I cannot bypass this issue. Any idea? im not be able to make the script work with my binance account. I try to change quantity, profit. i have  BNB Balance: 2.25157165. Any idea?

**Comment by yasinkuyu** [comment]
@nealgentry thanks https://github.com/yasinkuyu/binance-trader/commit/f80657fe14589f538ae2612ffbd3f63c9f8ace55
