### ISSUE TITLE
Bot increase speed

### ISSUE THREAD

**Issue by bestlinkXx** [yasinkuyu/binance-trader#42]
Hello everyone,

I need to know how is it possible to increase speed of this algorithm to buy/sell faster and improve profit to take best buyPrice.

Thank you !

**Comment by ykartal** [comment]
Hi @bestlinkXx ,
Give it a try; (Just a suggestion)
Removing lines about BTCUSDT  may increase the speed. This info is not important, it is just for information.
Update or comment;
line 143 and 157 in trader.py as;
143: ` #btcPrice = get_ticker("BTCUSDT")`
157: `print ('price:%.8f buyp:%.8f sellp:%.8f-bid:%.8f ask:%.8f' % (lastPrice, buyPrice, profitableSellingPrice, lastBid, lastAsk))`

**Comment by bestlinkXx** [comment]
Thank you !

**Comment by moonorblue** [comment]
Also, you can remove some unnecessary "print" callings before buy/sell, this might speed up a little bit.

**Comment by dscottboggs** [comment]
Have you tried running it with -OO?

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/56d1d2b1a8ea2b9a32f924a67f04c5c1f1bc2499
