### ISSUE TITLE
Problem to sell

### ISSUE THREAD

**Issue by bestlinkXx** [yasinkuyu/binance-trader#44]
Hello,

I have a problem to execute this condition : 

for order in ret:
        price = float(order['price'])
        origQty = float(order['origQty'])
        executedQty = float(order['executedQty'])

        if order['orderId'] == orderId:
            print ("Order: %d: %lf\t%lf\t%lf" % (order['orderId'], price, origQty, executedQty))
     
            TARGET_PROFITABLE_PRICE = None
            ORDER_ID = 0

Condition : order['orderId'] == orderId is impossible to achieve.

Anyone has a solution please ?

**Comment by bestlinkXx** [comment]
I tried to did it with get_orderbook() but any success.

**Comment by lumo7184** [comment]
Will someone show me how to implement this on binance? I will pay

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/cc674c5c1494212b3db3e95257d20e79c29f9e78
