### ISSUE TITLE
Error: Illegal characters found in parameter 'orderId'; legal range is '^[0-9]{1,20}$'.

### ISSUE THREAD

**Issue by perozu** [yasinkuyu/binance-trader#45]
Hi,
I didn't change any code, and the bot seems to work (it makes a few trades) but then terminates with this message:
Error: Illegal characters found in parameter 'orderId'; legal range is '^[0-9]{1,20}$'. 

Anyone else having these problems?

Sorry for closing and reopening, but I wasn't able to fix this by looking at resolved issues.

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/cc674c5c1494212b3db3e95257d20e79c29f9e78

**Comment by perozu** [comment]
No difference.
