### ISSUE TITLE
Stuck at saying "sell try again" instead of Selling

### ISSUE THREAD

**Issue by searchia** [yasinkuyu/binance-trader#47]
Hey,

First of all wanna say that it is an amazing bot that has been build, and would like to say a huge thanks to Yasinkuyu. 

The bot works fine with buying but has a problem when selling, and instead says "... sell try again...", anyone else have this problem? and know how to fix it?

Thank you so much on beforehand :)

**Comment by borocode** [comment]
just got the bot set up (mainly python set up lol) and having this error too.

**Comment by gcanteen** [comment]
I had this same issue when I tried about 12 hours ago, as well

**Comment by yasinkuyu** [comment]
I'il fix the bugs next weekend.

**Comment by bjeliazkov** [comment]
had this issue as well. think i see the problem.
looks like calc method is failing because lastBid is coming in as string rather than float.
that seems to clear out the error

**Comment by systemonkey** [comment]
@bjeliazkov can you let us know what needs to change to get rid of the error?

**Comment by bjeliazkov** [comment]
open trader.py in an editor and modify calc to make lastBid a float
eg.

original
"
def calc(lastBid):
    return lastBid + (lastBid * PROFIT / 100)
"

modified
"
def calc(lastBid):
    lastBid = float(lastBid)
    return lastBid + (lastBid * PROFIT / 100)
"

**Comment by systemonkey** [comment]
@bjeliazkov thanks for that. Unfortunately still running into issues.
Error: Illegal characters found in parameter 'orderId'; legal range is '^[0-9]{1,20}$'.
... sell try again...
I'll just wait for @yasinkuyu update. Much appreciate it.

**Comment by yasinkuyu** [comment]
@systemonkey https://github.com/yasinkuyu/binance-trader/issues/47#event-1405420092

**Comment by linhndd** [comment]
Thank you

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/56d1d2b1a8ea2b9a32f924a67f04c5c1f1bc2499
