### ISSUE TITLE
Bot Not Doing Anything?

### ISSUE THREAD

**Issue by dcloud102** [yasinkuyu/binance-trader#48]
Hi, I'm new to this.  I got python and the pip install requests set up.  I ran the bot and enter the ticker.  Bot ran and just list what your screenshot in the readme.  It doesn't do anything.  Could you elaborate on what it suppose to be doing?  

price: x.xxxxxx  buyp: x.xxxxxx  sellp: x.xxxxxx  bid: x.xxxxxx ask: x.xxxxxx

What is the price?  I'm assuming it's what the current price of the ticker.
What is buyp?  I'm guessing it is a predetermined price calculated to get the profit %?
What is sellp?  Selling price to make the profit %?
bid?
ask?

Thank you.

**Comment by linhndd** [comment]
yes, me too. But when I edit parameter orderid = 1. It's error ...sell try again... . And when is bot create new buy is good. But it can't auto sell again. I always manual sell it. how to fix it ?

**Comment by brahimioo** [comment]
I have exact the same problem, do we need to change the orderid?

**Comment by 420AnonymousJohn** [comment]
No today i've worked on the script and I think I found the solution. Running a few test and then I will bring you guys the solution! Will take about an hour.

Greetings,
420AnonymousJohn

**Comment by linhndd** [comment]
Lower your profit to 0.5 or 0.3% . It will be found and buy some coin faster

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/56d1d2b1a8ea2b9a32f924a67f04c5c1f1bc2499
