### ISSUE TITLE
Poor python logic/scripting + bug + suggestion

### ISSUE THREAD

**Issue by xdkreij** [yasinkuyu/binance-trader#50]
Not to offend anyone, i like the idea of the script.

But: **to start off**, you're current main(): fails

name=raw_input() <----------- makes no sense because "--symbol";  This causes the script to break!
Remove it AND the if name != statement, and the script works again.

while True <--------    while what True??? this way, its alway's true.....dafuq? :P

**Second**:

Define globals outsite of functions, they are globals.... put them at the top
e.g.

#Define Python imports
import os
import sys
import time
import config
import argparse

#Define Custom imports
from BinanceAPI import *

#Define Custom import vars
client = BinanceAPI(config.api_key, config.api_secret)

#Set globals
global DEBUG_MODE
global TEST_MODE

#Set parser
parser = argparse.ArgumentParser()
parser.add_argument("--quantity", type=float, help="Buy/Sell Quantity", default=6)
parser.add_argument("--symbol", type=str, help="Market Symbol (Ex: IOTABTC)", default='IOTABTC')
parser.add_argument("--profit", type=float, help="Target Profit", default=1.3)
parser.add_argument("--orderid", type=int, help="Target Order Id", default=0)
parser.add_argument("--testmode", type=bool, help="Test Mode True/False", default=False)
parser.add_argument("--debug",type=bool, help="Script debug mode True/False", default=False)
parser.add_argument("--wait_time", type=int, help="Wait Time (seconds)", default=3)
parser.add_argument("--increasing", type=float, help="Buy Price +Increasing (0.00000001)", default=0.00000001)
parser.add_argument("--decreasing", type=float, help="Sell Price -Decreasing (0.00000001)", default=0.00000001)
option = parser.parse_args()

#Define parser vars
TEST_MODE = option.testmode
DEBUG_MODE = option.debug
PROFIT = option.profit
ORDER_ID = option.orderid
QUANTITY = option.quantity
WAIT_TIME = option.wait_time  # seconds
WAIT_TIME_SELL = 4  # seconds

**Third**:

Might want to add a --debug option for output testing/verification

Let us know its on or off
 if DEBUG_MODE:
        print("DEBUG_MODE = ON.")
    else:
        print("DEBUG_MODE = OFF")

my 2 cents! Goodluck =D

**Comment by linhndd** [comment]
Can u guide enhance ? How to upgrade it? And what is function ?

**Comment by yasinkuyu** [comment]
I did some of these around. I plan to make extensive improvements during the weekend. Thx

**Comment by xdkreij** [comment]
np. Make sure you adhere to the binance API rules too.

Also, as a primary function: you can't buy with insufficient balance, check the balance after every successful buy order and choose to sell first if the balance is insufficient.
(Dynamic quantity for exponential growth might be an idea to )
