### ISSUE TITLE
Bot is buying but not selling?

### ISSUE THREAD

**Issue by brahimioo** [yasinkuyu/binance-trader#52]
First of all, thanks for making this script!

I have done everything like described, I can see the bot buying sometimes but it wont sell. 
Ive put the percentage on 1.3 - quantity on 100, and did wait for a long while, but it never did sell anything.

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/56d1d2b1a8ea2b9a32f924a67f04c5c1f1bc2499
