### ISSUE TITLE
Purchase with error

### ISSUE THREAD

**Issue by Jagermeister56** [yasinkuyu/binance-trader#54]
Script purchases but fails to see it properly. 
![screen shot 2018-01-05 at 12 41 40 am](https://user-images.githubusercontent.com/17785698/34631040-987b5ed4-f23c-11e7-82df-a92096c8979e.png)

then continues to try to drain all funds continuously purchasing over and over, instead of selling. 
![screen shot 2018-01-05 at 12 44 14 am](https://user-images.githubusercontent.com/17785698/34631060-acefa726-f23c-11e7-84a5-0144f6d23783.png)

**Comment by yasinkuyu** [comment]
Hello, https://github.com/yasinkuyu/binance-trader/issues/47#event-1405420092

**Comment by Jagermeister56** [comment]
those pictures aren't for selling, it doesn't detect that it purchased at all

**Comment by yasinkuyu** [comment]
@Jagermeister56 I'll fix it. Thank you.

**Comment by Jagermeister56** [comment]
awesome work BTW, thank you! very much appreciated!

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/56d1d2b1a8ea2b9a32f924a67f04c5c1f1bc2499
