### ISSUE TITLE
Not Buying or Selling

### ISSUE THREAD

**Issue by rkqths** [yasinkuyu/binance-trader#56]
Pls find below.
![image](https://user-images.githubusercontent.com/35159764/34637291-da70bd2c-f280-11e7-935e-9642ed78f07c.png)

Please, advice

**Comment by bernermic** [comment]
Same for me.

I'm totally new in Cryptocurrency so sorry if I missed something obvious ...

I'm using the first default setting: python trader.py --quantity 6 --symbol IOTABTC --profit 1.3 --wait_time 3 --orderid 0

![selection_272](https://user-images.githubusercontent.com/1283680/34639538-03d3bcc6-f2e2-11e7-9340-cd345096bb7b.jpg)

**Comment by linhndd** [comment]
Hi, please lower your profit. If it higher, you need to more time for waiting find buy and sell it

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/commit/56d1d2b1a8ea2b9a32f924a67f04c5c1f1bc2499
