### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by Bodek123** [yasinkuyu/binance-trader#57]
Hello,

I'd like to run your bot, but I get following error:

@yasinkuyu, 2017
Auto Trading for Binance.com. --symbol: XVNBTC
trader.py --symbol XVNBTC --quantity 1 --profit 1.3 --wait_time 1 --orderid 0 

%1.3 profit scanning for XVNBTC
... 

'lastPrice'
'lastPrice'
'lastPrice'
'bids'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "trader.py", line 320, in action
    buyPrice = lastBid + option.increasing
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

What to do? I'm not very good at python and linux :)

**Comment by yasinkuyu** [comment]
Invalid symbol name. Try XVGBTC.

https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

**Comment by Bodek123** [comment]
Thank You very much! :+1: 
PS You should then correct example in **Usage** table in README.md

**Comment by yasinkuyu** [comment]
I'm sorry for this fault/mistake. Fixed.
