### ISSUE TITLE
AttributeError: BinanceAPI instance has no attribute 'market_buy'

### ISSUE THREAD

**Issue by Tabakixan** [yasinkuyu/binance-trader#58]
Hi I have 2 errors: 
could you help please? 

first: 

> price:0.00040996   buyp:0.00040997 sellp:0.00041484-bid:0.00040996 ask:0.00040997
> Order(buy): DNTETH id:4839429, price:   0.00040393, orig_qty: 30.00000000
> price:0.00040996 buyp:0.00040997   sellp:0.00041484-bid:0.00040996 ask:0.00040997
> Profit loss, called order, 4839429
> Exception in thread Thread-140:
> Traceback (most recent call last):
> File "C:\Python27\lib\threading.py", line 801, in   __bootstrap_inner
> self.run()
> File "C:\Python27\lib\threading.py", line 754, in run
> self.__target(*self.__args, **self.__kwargs)
> File "trader.py", line 212, in check_buy
> buy = client.market_buy(symbol, quantity)
> AttributeError: BinanceAPI instance has   no attribute 'market_buy'

second:

> Order(buy): DNTETH   id:4830476, price: 0.00037251, orig_qty: 30.00000000
> price:0.00038000 buyp:0.00037254   sellp:0.00037707-bid:0.00037253 ask:0.00038000
> Error: UNKNOWN_ORDER
> Order Id: 4830504
> Order(buy): DNTETH id:4830480, price:   0.00037253, orig_qty: 30.00000000
> price:0.00037250 buyp:0.00037255   sellp:0.00037708-bid:0.00037254 ask:0.00038000
> Exception in thread Thread-282:
> Traceback (most recent call last):
> File "C:\ProgramData\Anaconda2\lib\threading.py", line 801,   in __bootstrap_inner
> self.run()
> File "C:\ProgramData\Anaconda2\lib\threading.py", line 754,   in run
> self.__target(*self.__args, **self.__kwargs)
> File "trader.py", line 122, in sell_limit
> print ("Profit: %%%s. Buy: %.8f Sell: %.8f" % (PROFIT,   buyPrice, sell_price))
> ##NameError: global name 'buyPrice' is not   defined

**Comment by yasinkuyu** [comment]
I can't test because there is no balance.
Thanks for info. I'm fixing it.
