### ISSUE TITLE
TypeError: float argument required, not unicode

### ISSUE THREAD

**Issue by borocode** [yasinkuyu/binance-trader#60]
thanks for the update, buy and sells working but getting this error making me think the bot isn't working as intended...

```
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Downloads\binance-trader-master (4)\binance-trader-master\trader.py", line 122, in sell_limit
    print ("Profit: %%%s. Buy: %.8f Sell: %.8f" % (PROFIT, order["price"], sell_price))
TypeError: float argument required, not unicode
```

**Comment by brewmium** [comment]
Didn't I see this same issue a few days ago? I'd make sure you have current source first thing

**Comment by borocode** [comment]
@brewmium https://github.com/yasinkuyu/binance-trader/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+unicode

**Comment by brewmium** [comment]
Same "type" error... but down on line 320 was the last fix.  Sorry, this is why I don't like untyped languages. :-)  I'm sure he will fix it. 

If it isn't happening to everyone...  it's an issu with your 'order["price"]' or 'sell_price' values being a string vs. a number.  check your inputs.

**Comment by borocode** [comment]
@yasinkuyu I _think_ it's working now. Excuse me for being illiterate but how does one use order id?
