### ISSUE TITLE
Error: Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by JAR3D** [yasinkuyu/binance-trader#63]
Hi, first off all, thank you for sharing this :)

I have the following error after a few loops:
![image](https://user-images.githubusercontent.com/7980158/34651679-f9e14442-f3ca-11e7-974c-a27e1902c101.png)
Can you help in what it may be causing this error?

**Comment by 001au** [comment]
I had this issue, and I'm running in docker for Mac.  I found through this [blog post](https://blog.shameerc.com/2017/03/quick-tip-fixing-time-drift-issue-on-docker-for-mac) that docker containers on Mac can experience time drift, especially after sleep.  Now I run this code whenever I get the 1000ms error:

`docker run --rm --privileged alpine hwclock -s`

I normally get about an hour or so before I have to run it again.  Hope it helps!

**Comment by JAR3D** [comment]
I'll try and see if it works. Thank you.

**Comment by JAR3D** [comment]
Hi, it didn't work :(

**Comment by 001au** [comment]
Perhaps make sure your system is synced with internet time?

**Comment by JAR3D** [comment]
yeah I'm trying to figure out. I'll keep you updated.

**Comment by JAR3D** [comment]
Hi, just seen somewhere how to work around this issue:

`int(time.time() * 1000 - 1000)`

Just subtract 1000 ms and it seems to solve the issue.

**Comment by yasinkuyu** [comment]
If the problem persists, issue may be reopened. Closed.

**Comment by Wrexen** [comment]
Where i have to add the code JAR3D posted ?

**Comment by burakhoruz** [comment]
https://i.hizliresim.com/vjazdO.png

Hi, it didn't work. How can I resolve the error.

**Comment by nadirdogan** [comment]
This is my solution for timestamps issue.
The code made equal windows time to binance server time.

from binance.client import Client
client = Client('api_key', 'api_secret')
import time
import win32api
gt = client.get_server_time()
aa = str(gt)
bb = aa.replace("{'serverTime': ","")
aa = bb.replace("}","")
gg=int(aa)
ff=gg-10799260
uu=ff/1000
yy=int(uu)
tt=time.localtime(yy)
win32api.SetSystemTime(tt[0],tt[1],0,tt[2],tt[3],tt[4],tt[5],0)

"The integer 10799260 for adjusting time zone and fine tuning for miliseconds."

**Comment by Maathouse** [comment]
Hi @nadirdogan, how often do you need to run that code?

**Comment by nadirdogan** [comment]
Hi @Maathouse, run the code needed depends on rtc of the pc. My pc needs least one run everyday. I set it to run automatic one a day.

**Comment by Roibal** [comment]
nadirdogan your code uses another python-binance git project, thanks for the info.
