### ISSUE TITLE
Changing pair

### ISSUE THREAD

**Issue by mcintirejohn4** [yasinkuyu/binance-trader#65]
When I try to run the program it says "the following arguments are required --symbol". I assume that means that I have to pick a pair to trade, but in the readme it says that there is a default. I tried changing "--symbol" to "XVGBTC" but that got me the error "XVGBTC is undefined". Anybody know how to add a pair to trade?

**Comment by 001au** [comment]
Are you running in docker?  Run this command from the project folder:

docker run -ti trader python trader.py --symbol XVGBTC

Can we add notes like this one to the docker run portion of readme?

**Comment by mcintirejohn4** [comment]
I'm not running in docker, I'm running from command prompt. I would run in docker but the install package doesn't boot up and it said docker was optional.

**Comment by mcintirejohn4** [comment]
I fixed it! After putting in my directory to cmd I entered "trader.py --symbol XVGBTC" and it ran. You can swap XVG for any pair, but to the creator, there is no default pair.

**Comment by 001au** [comment]
I thought I saw some commits over the weekend that show that XVGBTC is the default now.  Do you have a fresh download?

**Comment by mcintirejohn4** [comment]
Fresh download. I got it working, just had to add --symbol XVGBTC after
trader.py in cmd.
