### ISSUE TITLE
Buy/Sell problem

### ISSUE THREAD

**Issue by det-peralta** [yasinkuyu/binance-trader#67]
Hello i try to use the bot however, i cant make it work. im doing something wrong?

Command:
`python trader.py --symbol XVGETH --quantity 1 --profit 0.3 --loop 0 --orderid 0`

![untitled](https://user-images.githubusercontent.com/35231379/34681133-c0b2e07c-f492-11e7-9c92-025c9a431323.png)

When the buy/sell happens it will appear on the "Trade History" in binance website?

Thanks in advance

**Comment by 001au** [comment]
This seems the same as issue #27.  The solution in that thread worked for me.  Should the solution there make it to a commit?

**Comment by det-peralta** [comment]
Yes. the error is gone for me. After that #27 fix.

**Comment by det-peralta** [comment]
After resolve the previous issue, i have this one.

![capture](https://user-images.githubusercontent.com/35231379/34688573-7be265f4-f4aa-11e7-9b9d-ade51b287a29.PNG)

Any ideas?

**Comment by yasinkuyu** [comment]
@det-peralta fixed https://github.com/yasinkuyu/binance-trader/commit/f80657fe14589f538ae2612ffbd3f63c9f8ace55
