### ISSUE TITLE
Path problem on Sublim text

### ISSUE THREAD

**Issue by bestlinkXx** [yasinkuyu/binance-trader#7]
Hello,

I have this problem : 

[Decode error - output not utf-8]
[cmd:  [u'python', u'-u', u'C:\\Users\\Julien\\Desktop\\binance-trader-master\\trader.py']]
[dir:  C:\Users\Julien\Desktop\binance-trader-master]
[path: C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Live\Shared;C:\Python36;]
[Finished]

I don't know how to fix PATH problem ?

Thank you

**Comment by yasinkuyu** [comment]
Try Python 2.7

**Comment by bestlinkXx** [comment]
I fixed it thank you.
