### ISSUE TITLE
Error: Filter failure: MIN_NOTIONAL

### ISSUE THREAD

**Issue by DavidLanz** [yasinkuyu/binance-trader#70]
running script, showing:

Error: Filter failure: MIN_NOTIONAL

![image](https://user-images.githubusercontent.com/186812/34702967-8184f1f8-f52b-11e7-830f-ef4b4280f73a.png)

command: 
python trader.py --symbol XVGBTC --quantity 10 --profit 0.3 --loop 0 --orderid 0

please help!

**Comment by DavidLanz** [comment]
i spent all my btc but can't sell at low price, so my BTC is low below 0.001...

case closed

btw, can we set the amount of my btc to place order?

**Comment by yasinkuyu** [comment]
@DavidLanz --quantity XXX

**Comment by VasTShadowZz** [comment]
Failure
Filter failure: MIN_NOTIONAL
https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

Filter failure: PRICE_FILTER
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by JAR3D** [comment]
Hi see below:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md
