### ISSUE TITLE
trader.py: error: argument --quantity: invalid int value: '0.1'

### ISSUE THREAD

**Issue by DavidLanz** [yasinkuyu/binance-trader#71]
can we put float in --quantity? or must int?

![image](https://user-images.githubusercontent.com/186812/34704011-1e5a5fc2-f531-11e7-9693-83113bd37721.png)

**Comment by yasinkuyu** [comment]
Fixed. int to float https://github.com/yasinkuyu/binance-trader/commit/bff07b9d191fda3148a6a2af30e06f2454ec4346#diff-83750037e0c08b5bf4f07964f9481689R15
