### ISSUE TITLE
Open open anymore

### ISSUE THREAD

**Issue by VasTShadowZz** [yasinkuyu/binance-trader#73]
not sure what happened. Was just working and now wont open with cmd

![image](https://user-images.githubusercontent.com/11942372/34711155-3e7ae1b8-f4ec-11e7-9e55-5c8c0420c621.png)

**Comment by linhndd** [comment]
Make sure you installed python and import easy_install requests

**Comment by DavidLanz** [comment]
type command below to check if your Python install requests package.

pip show requests

and, --profit 0.3 ?? as i know transaction on binance.com will cost each order 1% fee? correct if i am wrong...

**Comment by VasTShadowZz** [comment]
Both easy_install and pip requests are downloaded, no clue what happened like i said it was just working

**Comment by VasTShadowZz** [comment]
Both easy_install and pip requests are downloaded, no clue what happened like i said it was just working

**Comment by Foof811** [comment]
try idle.bat in your python folder and see if that works.

**Comment by VasTShadowZz** [comment]
um......... fould it.... 0KB is kinda small. it somehow deleted itself tf :/
