### ISSUE TITLE
Error: Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by borocode** [yasinkuyu/binance-trader#74]
![image](https://user-images.githubusercontent.com/20490856/34728065-d03ca2c8-f526-11e7-9632-6be2c3185687.png)
Not sure what to do, I Ctrl+C'd at the end

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/binance-trader/issues?utf8=%E2%9C%93&q=is%3Aissue+Timestamp

**Comment by borocode** [comment]
not sure what was wrong but restarted my PC and looks like it's back working.
