### ISSUE TITLE
More then 1 pair at a time

### ISSUE THREAD

**Issue by MIKEYCRYPTO** [yasinkuyu/binance-trader#76]
Hello all !!! 

Currently I run the bot with a setting of 

First Window
"python trader.py --symbol TRXETH --quantity 100 --profit 1.5 --loop 0 --orderid 0 --prints true                --stoploss 6"

Second window
"python trader.py --symbol XVGETH --quantity 100 --profit 1.5 --loop 0 --orderid 0 --prints true               --stoploss 6"

Third window
"python trader.py --symbol XRPETH --quantity 50 --profit 1.5 --loop 0 --orderid 0 --prints true                  --stoploss 6"

Running from Windows 10 and windows 7 ( day and night computers )

I can see the program buying, but never selling anything. Even if the price drops more then 6% with any pair.   Am I doing something wrong?

All comments are appreciated.

Sorry for the screen wrap with the coding snips

**Comment by VasTShadowZz** [comment]
Same problem showed in #66?

**Comment by MIKEYCRYPTO** [comment]
I have BNB turned off in my settings because of the constant purchasing of coins .

I had .5 eth and after running the bot, i had zillions of coins, and no eth left... Just kept buying and buying . Never selling even when the price dropped.

Then I got the error of Insufficent Funds....
I didnt lose any $$ at all, my ETH balance just got spread around .

Is there any fix for the program to sell at some point?

**Comment by Jagermeister56** [comment]
-stoploss i don't think stoploss is working yet

**Comment by yasinkuyu** [comment]
--stop_loss is not ready yet. https://github.com/yasinkuyu/binance-trader/issues/66#issuecomment-357409752
