### ISSUE TITLE
No JSON object could be decoded : Exception in thread Thread-3869:

### ISSUE THREAD

**Issue by VasTShadowZz** [yasinkuyu/binance-trader#77]
`price:0.00001408 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001408 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001410
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
No JSON object could be decoded
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
Exception in thread Thread-3869:
Traceback (most recent call last):
  File "C:\Python27\Lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "C:\Python27\Lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\binance-trader-master\trader.py", line 338, in action
    print ('price:%.8f buyp:%.8f sellp:%.8f-bid:%.8f ask:%.8f' % (lastPrice, buyPrice, profitableSellingPrice, lastBid, lastAsk))
TypeError: float argument required, not NoneType

price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001410
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001410
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001410
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001410
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001410 sellp:0.00001413-bid:0.00001409 ask:0.00001410
price:0.00001410 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409
price:0.00001409 buyp:0.00001409 sellp:0.00001412-bid:0.00001408 ask:0.00001409`

**Comment by yasinkuyu** [comment]
Fixed. Check devx branch
