### ISSUE TITLE
Failure : Price Filter

### ISSUE THREAD

**Issue by kamsy26** [yasinkuyu/binance-trader#78]
Hi, I set up the bot, but I do not understand my mistakes or my limitations. here is my argument:
python trader.py --symbol RCNBNB --quantity 200 --profit 3 --loop 0 --orderid 0. But it returns to me the error "Failure: Price Filter." Can you help me please.
Thank you

**Comment by VasTShadowZz** [comment]
Failure
Filter failure: MIN_NOTIONAL
https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule

Filter failure: PRICE_FILTER
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by det-peralta** [comment]
Can someone explain this to me. I cannot be able to make it work.
eg:
python trader.py --symbol OSTBNB --quantity 10 --profit 0.3

If i have 2.25157165 BNB balance why i getting the error?

**Comment by Jagermeister56** [comment]
because minimum purchase must equal 1BNB  @VasTShadowZz already explained this in MIN_NOTIONAL

**Comment by det-peralta** [comment]
My purchase is more than 1BNB. I  cant make it work.

eg.
50 RCN * 0.02808001 BNB = 1.4040005 BNB

The total is more than 1BNB

**Comment by C2BB** [comment]
You need to set the increase and decrease parameters to align to BNB.

Ex. --increasing .00001 --decreasing .00001

**Comment by det-peralta** [comment]
@C2BB thank you for the reply. Now im getting this. This would much easier if we can see the total output values .

```
python trader.py --symbol RCNBNB --quantity 40 --profit 0.5 --increasing .0000
1 --decreasing .00001 --loop 1
@yasinkuyu, 2017
Auto Trading for Binance.com. --symbol: RCNBNB
trader.py --symbol RCNBNB --quantity 40 --profit 0.5 --wait_time 1 --orderid 0

%0.5 profit scanning for RCNBNB
...

price:0.02378000 buyp:0.02343000 sellp:0.02353710-bid:0.02342000 ask:0.02378000
price:0.02378000 buyp:0.02343000 sellp:0.02353710-bid:0.02342000 ask:0.02378000
Error: Filter failure: MIN_NOTIONAL
Error: Filter failure: MIN_NOTIONAL
```
