### ISSUE TITLE
Buying at market value?

### ISSUE THREAD

**Issue by Jagermeister56** [yasinkuyu/binance-trader#82]
Why is this even a feature? All it does it buy it at the highest possible point and then waits for it to tank and tries to buy more. 
![screen shot 2018-01-10 at 4 33 47 pm](https://user-images.githubusercontent.com/17785698/34796661-28fe537c-f624-11e7-8928-40141886f5fa.png)
![screen shot 2018-01-10 at 4 27 07 pm](https://user-images.githubusercontent.com/17785698/34796664-2a82c8b8-f624-11e7-8c48-417674e2664f.png)

**Comment by linhndd** [comment]
Yes, me too. that's problem. I look bot buy with a lower price, and when it think price will be higher, it called order and buy with market price. And it buy and buy but don't sell again ?

http://prntscr.com/hyrql0

**Comment by Jagermeister56** [comment]
yeah exactly, it's really killing me lol
