### ISSUE TITLE
Redundant code (find in trader.py, def action())?

### ISSUE THREAD

**Issue by JAR3D** [yasinkuyu/binance-trader#83]
Hi, I just wonder if this isn't a redundant code (find in trader.py, def action()):

`    
   if lastAsk >= profitableSellingPrice or option.orderid > 0:  
        
       (...)
        
        if orderId is not None:
             (...)
`

I think the second if is not necessary. Can you confirm? Thnaks

**Comment by yasinkuyu** [comment]
No, actually it is necessary. But it has not been completed yet. You should wait for the Release. If you have the ability, please send a pull-request with improvement.

**Comment by JAR3D** [comment]
Hello, sorry but I'm a little noob in this area, I'm just giving my first steps, and really I don't know how to work with git very well. Just trying to understand your code and made some tests:
`if lastAsk >= profitableSellingPrice or option.orderid > 0:  
        
        # Manually defined --orderid, try to sell ( use balance.py )
        if option.orderid > 0 :
            orderId = option.orderid
        else:
            orderId = 859 #manually added
    
        # Order book prices
        #newLastBid, newLastAsk = get_order_book(symbol)
        #newSellPrice = newLastAsk - option.decreasing 
        print('test1')
        if orderId is not None:
            print('test2')`

When I run this piece of code it always prints test1 and test2. If it enters the first 'if' I don't see how to not enter the second 'if'.

**Comment by yasinkuyu** [comment]
@JAR3D I'm doing some improvements. You can follow devx branch. https://github.com/yasinkuyu/binance-trader/commit/f80657fe14589f538ae2612ffbd3f63c9f8ace55
