### ISSUE TITLE
Profit loss, called order

### ISSUE THREAD

**Issue by C2BB** [yasinkuyu/binance-trader#84]
After every purchase order "Profit loss, called order" takes place selling at market price (usually for a loss). Is anyone else running into this?

python trader.py --symbol XLMBNB --quantity 40 --profit 0.5 --increasing .00001 --decreasing .00001 --loop 1 
@yasinkuyu, 2017
Auto Trading for Binance.com. --symbol: XLMBNB
trader.py --symbol XLMBNB --quantity 40 --profit 0.5 --wait_time 1220 --orderid 0

%0.5 profit scanning for XLMBNB
...

price:0.02810000 buyp:0.02796000 sellp:0.02808975-bid:0.02795000 ask:0.02957000
Order Id: 906048
Profit: %0.5. Buy: 0.02955000 Sell: 0.02955000
Order(buy): XLMBNB id:906048, price: 0.02796000, orig_qty: 40.00000000
Profit loss, called order, 906048
Order(buy): XLMBNB id:906048, price: 0.02796000, orig_qty: 40.00000000
Order(buy): XLMBNB id:906048, price: 0.02796000, orig_qty: 40.00000000
Order(buy): XLMBNB id:906048, price: 0.02796000, orig_qty: 40.00000000
Order(buy): XLMBNB id:906048, price: 0.02796000, orig_qty: 40.00000000
Order(buy): XLMBNB id:906048, price: 0.02796000, orig_qty: 40.00000000
Order(buy): XLMBNB id:906048, price: 0.02796000, orig_qty: 40.00000000
Order(buy): XLMBNB id:906048, price: 0.02796000, orig_qty: 40.00000000
Order(buy): XLMBNB id:906048, price: 0.02796000, orig_qty: 40.00000000
Order(buy): XLMBNB id:906048, price: 0.02796000, orig_qty: 40.00000000

**Comment by Charlita** [comment]
@yasinkuyu would this have anything to do with the fee amount in trader.py. Currently set to "0.0005" but on binance it shows "Fee: --0.10%-- 0.050%"

**Comment by yasinkuyu** [comment]
Fee is not yet calculated.
