### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by gabrielpinhobr** [yasinkuyu/binance-trader#86]
I set the parameters as suggested, everething look great and working, but I didn't understand what means the number on the lines...

I belive the 1st is the market price, but what does mean buyp, sellp, bid and ask? The screen shows the target prices?

Another question :-P .... The screen shoes some notification when it buy or sell?

Even if I set profit to 0.3 the system didn't sent orders.  :-(

Sorry again for the so noob question. #

**Comment by yasinkuyu** [comment]
buyp = buy price. First bid +1 (or --increasing)
sellp = sell price Last ask -1 (or --decreasing)

Between bid and ask prices for orders --profit must be profitable.
This profit may not be all the time.

**Comment by gabrielpinhobr** [comment]
The program is able to sell coin that I already have. Or I need to keep some BTC in the funds?
