### ISSUE TITLE
Filter failure: PRICE_FILTER

### ISSUE THREAD

**Issue by det-peralta** [yasinkuyu/binance-trader#87]
I tested with [fix](https://github.com/yasinkuyu/binance-trader/commit/f80657fe14589f538ae2612ffbd3f63c9f8ace55) and:

![222](https://user-images.githubusercontent.com/35231379/34905987-b3e01f96-f85b-11e7-8ca6-ce58d391bc96.PNG)

if i add:

` --increasing .00001 --decreasing .00001`

![33](https://user-images.githubusercontent.com/35231379/34905989-b4f8b51e-f85b-11e7-96e7-30fa52919ce1.PNG)

thank your for the hard work

**Comment by yasinkuyu** [comment]
- Some coins may need to change the value of --increasing XXX.

- No such table: orders error indicates that the orders.db database can not be found.
Rename config.sample.py to config.py / db/orders.sample.db to orders.db

-Do you have as many BNB in your account?

**Comment by det-peralta** [comment]
2.06807338 BNB

![sssdd](https://user-images.githubusercontent.com/35231379/34906274-156686e6-f862-11e7-8a7c-5bc0ebcf1440.PNG)

**Comment by det-peralta** [comment]
[fix](https://github.com/yasinkuyu/binance-trader/commit/abe09813349269dcd95d2bee2a47e0062f3e9464) output

![capture](https://user-images.githubusercontent.com/35231379/34906324-48de3fb8-f863-11e7-9416-911d7950c60e.PNG)

**Comment by rickdeaconx** [comment]
I am encountering a similar error. Buy succeeds - sell succeeds. Account balance returns to > what it was prior.

price:0.00024754 buyp:0.00025754 sellp:0.00024878-bid:0.00024754 ask:0.00025985
Buy order created id:3964797, q:250.00000000, p:0.00025754
Order (Filled) Id: 3964797
LastPrice : 0.00024754
Profit: %0.5. Buy price: 0.00024878 Sell price: 0.00024878
m: Account has insufficient balance for requested action.
m: Account has insufficient balance for requested action.
m: Account has insufficient balance for requested action.
