### ISSUE TITLE
ints and floats

### ISSUE THREAD

**Issue by masterdam79** [yasinkuyu/binance-trader#89]
Hi all,

Nice work!
Trying this script the following caught my attention.

1) The readme explains you can use floats for the quantity, but that fails:
```
trader.py: error: argument --quantity: invalid int value: '0.1'
```

2) Everytime the script wants to increase or decrease the script fails on that iteration with the following:
```
  File "trader.py", line 327, in action
    buyPrice = lastBid + option.increasing
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

So there seems to be something which I haven't figured out yet, will fllow up when I know more.

**Comment by linhndd** [comment]
Hi, i think you can fix it at trader.py, line 13

`parser.add_argument("--quantity", type=int, help="Buy/Sell Quantity", default=6)`

You can change type=int to type=float .

**Comment by Charlita** [comment]
The devx branch has --quantity set as float, I'm guessing you are using master, you may want to give that a try!
