### ISSUE TITLE
How Do I Get This Working In Windows And Getting Requests

### ISSUE THREAD

**Issue by Foof811** [yasinkuyu/binance-trader#9]
So I've managed to run the program using the idle.bat from Python 2.7 (Then using F5 to run it), but whenever I run it, it says that there is no module called requests. I saw a way to install them, but those are with linux commands. How do I get Requests for Windows? Also, is there anything I need to edit besides adding API keys to config.py?

**Comment by caiorondon** [comment]
Well, I use Windows Bash.

But that should work.

https://stackoverflow.com/questions/1449494/how-do-i-install-python-packages-on-windows

**Comment by Foof811** [comment]
I have Windows 7 so I'm not sure Bash is an option for me. But at this point with all the run around and trying to figure out how to import the requests, I might as well wait for it to be packaged as an .exe or something.
