### ISSUE TITLE
Error: bl: no such table: orders

### ISSUE THREAD

**Issue by rickdeaconx** [yasinkuyu/binance-trader#92]
Got this error after a buy was successful. Application error'd after and didn't sell.

Also experienced a similar error stating orderid wasn't what it expected with a regex next to it.

price:0.00117770 buyp:0.00118150 sellp:0.00117970-bid:0.00117150 ask:0.00118680
bl: no such table: orders
price:0.00117510 buyp:0.00118160 sellp:0.00117980-bid:0.00117160 ask:0.00118680
m: Account has insufficient balance for requested action.

**Comment by yasinkuyu** [comment]
db/orders.sample.db -> orders.db

**Comment by dreKion** [comment]
I have the same error, I have renamed orders.sample.db to orders.db. Only occurs in some coins, If I try with ADA works.

**Comment by rickdeaconx** [comment]
@yasinkuyu thanks - fixed it.

Encountering an error where it buys/sells successfully and says:
m: Account has insufficient balance for requested action.

Despite being > the amount it started with.

**Comment by yasinkuyu** [comment]
@rickdeaconx There is a problem in the loop. Once an order is complete, it can not go to the other order. I'm looking at.
