### ISSUE TITLE
Invalid docker file

### ISSUE THREAD

**Issue by omerfarukz** [yasinkuyu/binance-trader#94]
Hi, modified docker file for build. Executed docker run trader command as described in readme file. There is an error occurs while execution. 

docker run trader 
Traceback (most recent call last):
  File "./trader.py", line 9, in <module>
    from Trading import Trading
ModuleNotFoundError: No module named 'Trading'

**Comment by elCapitanoh** [comment]
Yeah, seems like the dev hasn't updated it to work with the new folders.
