### ISSUE TITLE
Error: Timestamp

### ISSUE THREAD

**Issue by dreKion** [yasinkuyu/binance-trader#97]
`price:0.00038749 buyp:0.00038314 sellp:0.00038581-bid:0.00038313 ask:0.00038870
price:0.00038749 buyp:0.00038314 sellp:0.00038581-bid:0.00038313 ask:0.00038870
Error: Timestamp for this request was 1000ms ahead of the server's time.
Error: Timestamp for this request was 1000ms ahead of the server's time.
price:0.00038749 buyp:0.00038314 sellp:0.00038581-bid:0.00038313 ask:0.00038869
price:0.00038749 buyp:0.00038314 sellp:0.00038581-bid:0.00038313 ask:0.00038869
price:0.00038749 buyp:0.00038314 sellp:0.00038581-bid:0.00038313 ask:0.00038869
Error: Timestamp for this request was 1000ms ahead of the server's time.
Error: Timestamp for this request was 1000ms ahead of the server's time.`

How solve?, It purcharsed but never sell with timestamp error.

**Comment by yasinkuyu** [comment]
Readme;
Timestamp for this request was 1000ms ahead of the server's time.
https://github.com/yasinkuyu/binance-trader/issues/63#issuecomment-355857901

**Comment by dreKion** [comment]
ok thanks
