### ISSUE TITLE
bl: no such table: orders

### ISSUE THREAD

**Issue by Jagermeister56** [yasinkuyu/binance-trader#99]
![screen shot 2018-01-16 at 2 18 00 am](https://user-images.githubusercontent.com/17785698/34976231-9685bf14-fa63-11e7-94e4-5045e1c84e02.png)

**Comment by masterdam79** [comment]
I solved this by copying the values.sample.db to values.db before starting

**Comment by masterdam79** [comment]
Sorry db/orders.sample.db to db/orders.db

**Comment by Jagermeister56** [comment]
yeah just figured it out lol my bad
